const {test,expect}=require('@playwright/test');test.use({serviceWorkers:'block',reducedMotion:'reduce'});
async function boot(page,width){const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.setViewportSize({width,height:900});await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await page.goto(base+'/?verify=aftershock-sequences');await page.waitForFunction(()=>window.AftershockSequence&&window.__mgMapReady&&!__fetchGlobalFeedsEmAndamento);await page.evaluate(()=>{pausarBuscas();clearTimeout(cycleTimeout);pendingNewCameraQuakes.clear();pendingQuakeRevisions.clear();stopWaveFront();stopFeltZone();SeismicCinema.stop();globalAlerts=[];const now=Date.now();globalEvents=[{id:'main-qa',type:'earthquake',mag:6.6,depth:10,coords:[-80.8,7.5],time:now-3600000,place:'Panama',source:'QA'},{id:'child-qa',type:'earthquake',mag:4.2,depth:12,coords:[-80.6,7.5],time:now-600000,place:'Panama',source:'QA'},{id:'unrelated-qa',type:'earthquake',mag:3,depth:10,coords:[30,38],time:now-600000,place:'Turkey',source:'QA'}];AftershockSequence.refresh();showEventDetails(0,false);clearTimeout(cycleTimeout);clearTimeout(window.__mgWaveDelayT);clearTimeout(window.__mgRadarDelayT);SeismicCinema.stop();fecharViradaCardAlcance();});}
for(const width of [1280,390])test('sequence renders principal and possible replicas, details navigate and other event cleans up '+width,async({page})=>{
 await boot(page,width);await expect(page.locator('#pd-aftershocks-summary')).toContainText('Possíveis réplicas · 1');await expect(page.locator('#pd-aftershocks-summary')).toContainText('M6,6');await expect(page.locator('.aftershock-pin')).toHaveCount(2);await expect(page.locator('.aftershock-pin.main')).toContainText('Principal · M6,6');
 await page.evaluate(()=>{syncAllMarkers();});expect(await page.evaluate(()=>markerStores.quake.get('main-qa').getElement().classList.contains('aftershock-covered'))).toBe(true);
 if(width===390)await page.evaluate(()=>abrirPainelDetalhesMobile());await page.locator('#pd-aftershocks-summary button').click();await expect(page.locator('#pd-details-verso')).toContainText('Associação estimada');await page.locator('#pd-aftershocks button').filter({hasText:'M4,2'}).click();await expect(page.locator('#pd-mag')).toContainText('4,2');expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('child-qa');expect(await page.evaluate(()=>AftershockSequence.state().mainId)).toBe('main-qa');
 await page.evaluate(()=>{showEventDetails(2,false);clearTimeout(cycleTimeout);});await expect(page.locator('#pd-aftershocks-summary')).toHaveCount(0);await expect(page.locator('.aftershock-pin')).toHaveCount(0);expect(await page.evaluate(()=>markerStores.quake.get('main-qa')?.getElement().classList.contains('aftershock-covered')||false)).toBe(false);
});
test('new arrivals update quietly, revisions do not replay and tsunami coast hides the sequence',async({page})=>{
 await boot(page,1280);await page.clock.install();await page.clock.pauseAt(await page.evaluate(()=>Date.now()+1000));
 const before=await page.evaluate(()=>{stopWaveFront(true);stopMapCamera();map.jumpTo({center:[-80.8,7.5],zoom:6});return {center:map.getCenter().toArray(),zoom:map.getZoom()};});
 await page.evaluate(()=>{globalEvents.push({...globalEvents[1],id:'new-child',time:Date.now(),coords:[-80.5,7.6],mag:4.6});EventStore.notify('filter',{});});await expect(page.locator('#pd-aftershocks-summary')).toContainText('Possíveis réplicas · 2');await expect(page.locator('.aftershock-pin.fresh')).toHaveCount(1);expect(await page.evaluate(()=>({center:map.getCenter().toArray(),zoom:map.getZoom()}))).toEqual(before);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('main-qa');
 await page.evaluate(()=>{globalEvents[0]={...globalEvents[0],mag:6.8};AftershockSequence.refresh();});await expect(page.locator('.aftershock-pin.main')).toContainText('M6,8');await page.clock.fastForward(10100);await expect(page.locator('.aftershock-pin.fresh')).toHaveCount(0);
 await page.evaluate(()=>{globalEvents[1]={...globalEvents[1],mag:4.3};AftershockSequence.refresh();const q=globalEvents[0];globalAlerts=[{id:'tsunami-sequence-qa',type:'tsunami',official:true,source:'PTWC',coords:q.coords,originTime:q.time,originMag:q.mag,time:Date.now(),place:'Panama',hazardNature:'warning',warningLevel:'Aviso',affectedAreas:[{name:'Panama',category:'1 TO 3 METERS'}]}];TsunamiLinkedPanel.refresh();});await expect(page.locator('.aftershock-pin.fresh')).toHaveCount(0);await page.waitForFunction(()=>map.getSource('tsunami-official-regions')?.serialize().data.features.length>0);await page.clock.fastForward(15500);expect(await page.evaluate(()=>TsunamiPresentation.state().phase)).toBe('coast');expect(await page.evaluate(()=>[...document.querySelectorAll('.aftershock-pin')].every(el=>el.style.display==='none'))).toBe(true);await page.clock.fastForward(10000);await expect(page.locator('.aftershock-pin.main')).toBeVisible();
});
test('map stays bounded with a large sequence, without changing catalog or rotation',async({page})=>{
 await boot(page,1280);await page.evaluate(()=>{for(let i=0;i<100;i++)globalEvents.push({...globalEvents[1],id:'many-'+i,time:Date.now()-i*2000,coords:[-80.7+i*.001,7.55],mag:3+i*.01});AftershockSequence.refresh();});expect(await page.evaluate(()=>AftershockSequence.state().count)).toBe(101);expect(await page.locator('.aftershock-pin').count()).toBeLessThanOrEqual(41);expect(await page.evaluate(()=>globalEvents.length)).toBe(103);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('main-qa');
});
