const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');test.use({serviceWorkers:'block'});
const cases=[['storm','rain-slide',{}],['hurricane','spiral-flight',{windKmh:150}],['hurricane','squall-slip',{classification:'TS',windKmh:85}],['hurricane','squall-slip',{classification:'TD',windKmh:45}],['tornado','vortex-lift',{}],['tsunami','word-wash',{}],['flood','floating',{}],['fire','charred',{}],['volcano','ember-break',{detail:'Fluxo de lava ativo'}],['volcano','ash-break',{detail:'Emissão de cinzas · sem lava'}],['volcano','monitoring',{detail:'Sem atividade eruptiva'}],['earthquake','fallen',{mag:5.9}]];
for(const width of [1280,390])test('cada evento reage com suas letras, preserva dados e restaura aos 16 segundos '+width,async({page})=>{
 await page.setViewportSize({width,height:844});await page.setContent('<body class="mobile-details-open"><div id="painel-direito" style="position:relative;width:320px;height:600px;overflow:hidden;background:#0b2231;color:white;font:18px system-ui"><div id="pd-local" style="margin:130px 18px 25px">Evento extremo em São Paulo 🇧🇷</div><div id="pd-source">Fonte oficial · boletim atualizado</div><div class="stat-card" style="margin-top:100px"><span class="stat-card-label">Intensidade</span><span class="stat-card-value"><b style="color:rgb(240,210,120)">150</b> km/h</span></div><button id="control" style="position:absolute;top:12px;right:12px">Detalhes</button></div></body>');
 for(const f of ['painel-fx.css','cinematic-card.css','card-event-typography.css'])await page.addStyleTag({content:fs.readFileSync(path.join(__dirname,'../css',f),'utf8')});
 await page.evaluate(()=>{window.__frame=null;requestAnimationFrame=fn=>(__frame=fn,1);cancelAnimationFrame=()=>{__frame=null;};window.CardCinemaFilm={create:()=>null,footage:()=>null};window.CardWeatherPhysics={create:()=>null};});
 for(const f of ['painel-fx.js','card-flood-rise.js','card-event-typography.js','cinematic-card.js'])await page.addScriptTag({content:fs.readFileSync(path.join(__dirname,'../js',f),'utf8')});
 const original=await page.locator('#painel-direito').innerText();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const [type,reaction,extra] of cases){
  const state=await page.evaluate(({type,reaction,extra})=>{const begin=performance.now();CinematicCard.start({id:'type-'+reaction,type,...extra});for(const t of [.3,1,2,3,4,5.5,6.5,8,10,12])__frame(begin+t*1000);const p=document.getElementById('painel-direito'),nodes=Array.from(p.querySelectorAll('[data-event-reaction]'));window.__sceneBegin=begin;return {reaction:nodes.some(n=>n.dataset.eventReaction===reaction),hidden:nodes.some(n=>getComputedStyle(n).opacity==='0'),word:p.querySelectorAll('.pd-fx-windword[data-event-reaction=word-wash]').length,flag:Array.from(p.querySelectorAll('#pd-local .pd-fx-windletter')).filter(n=>n.textContent==='🇧🇷').length};},{type,reaction,extra});
  expect(state.reaction,reaction).toBe(true);expect(state.flag).toBe(1);if(reaction==='word-wash')expect(state.word).toBeGreaterThan(0);if(['charred','ember-break','ash-break','vortex-lift','spiral-flight','squall-slip','rain-slide'].includes(reaction))expect(state.hidden,reaction).toBe(true);if(reaction==='monitoring'){expect(state.hidden).toBe(false);await expect(page.locator('[data-event-reaction=monitoring]')).not.toHaveCount(0);expect(await page.locator('[data-event-reaction]').evaluateAll(a=>a.every(el=>!el.style.clipPath&&!el.style.filter))).toBe(true);}
  expect(await page.locator('#painel-direito').innerText()).toBe(original);await expect(page.locator('.stat-card-value b')).toHaveCSS('color','rgb(240, 210, 120)');await page.locator('#control').click();
  await page.evaluate(()=>__frame(__sceneBegin+16100));await expect(page.locator('.pd-cinema-layer,.pd-letter-fragments,.pd-fx-windletter,[data-event-reaction]')).toHaveCount(0);expect(await page.locator('#painel-direito').innerText()).toBe(original);
 }
 expect(errors).toEqual([]);
});
for(const width of [1280,390])test('Menu e eventos reais compartilham letras, revisão, controles e limpeza '+width,async({page})=>{
 test.setTimeout(180000);const site=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.setViewportSize({width,height:844});await page.route('**/*',r=>new URL(r.request().url()).hostname===new URL(site).hostname?r.continue():r.abort());await page.goto(site+'/?verify=event-typography-'+Date.now(),{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento&&!!window.CardEventTypography);
 await page.evaluate(()=>{pausarBuscas();globalEvents=[];pendingNewCameraQuakes.clear();pendingQuakeRevisions.clear();const item={id:'typography-real',type:'storm',detail:'Trovoadas e chuva intensa',source:'QA',place:'São Paulo — teste da tipografia 🇧🇷',coords:[-46.63,-23.55],sev:3,time:Date.now()};globalAlerts=[item];upsertAlert(item);showAlertDetails(item,false);clearTimeout(cycleTimeout);clearTimeout(window.__mgRadarDelayT);clearTimeout(window.__mgWaveDelayT);if(innerWidth<900){document.body.classList.remove('mobile-details-mid');document.body.classList.add('mobile-details-open');}});
 await expect(page.locator('#pd-local')).toContainText('teste da tipografia',{timeout:20000});await page.clock.install();await page.clock.pauseAt(await page.evaluate(()=>Date.now()+1000));
 await page.evaluate(()=>CinematicCard.start(EventStore.getSelected()));await page.clock.runFor(300);const field=await page.locator('.pd-letter-fragments').elementHandle();
 await page.evaluate(()=>{const item={...EventStore.getSelected(),place:'São Paulo — boletim atualizado 🇧🇷'};upsertAlert(item);showAlertDetails(item,false,true);clearTimeout(cycleTimeout);});await page.clock.runFor(2000);expect(await field.evaluate(el=>el.isConnected)).toBe(true);await expect(page.locator('#pd-local')).toContainText('boletim atualizado');await page.clock.fastForward(13700);await page.clock.runFor(100);await expect(page.locator('.pd-cinema-layer')).toHaveCount(0);
 const headline=await page.locator('#pd-local').textContent();
 for(const key of ['storm','typhoon','tropical-storm','depression','tornado','tsunami','flood','fire','volcano-lava','volcano-ash','volcano-monitoring']){
  await page.evaluate(key=>CardEffectDemo.preview(key),key);await expect(page.locator('#card-fx-demo-status')).toContainText('16 s');await page.clock.fastForward(3100);await page.clock.runFor(100);await page.clock.fastForward(2200);await page.clock.runFor(100);
  await expect(page.locator('[data-event-reaction]')).not.toHaveCount(0);await expect(page.locator('#pd-local')).toHaveText(headline);
  expect(await page.locator('#pd-focus-btn').evaluate(el=>{const r=el.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('#pd-focus-btn')===el;})).toBe(true);
  await page.screenshot({path:'/tmp/typography-'+key+'-'+width+'.png'});await page.clock.fastForward(10600);await page.clock.runFor(100);await expect(page.locator('.pd-cinema-layer,.pd-letter-fragments,.pd-fx-windletter,#card-fx-demo-status')).toHaveCount(0);await expect(page.locator('#pd-local')).toHaveText(headline);
 }
 await page.evaluate(()=>SeismicCinema.play({mag:5.9,depth:10},'manual',true));await page.clock.fastForward(3100);await page.clock.runFor(100);await expect(page.locator('[data-event-reaction=fallen]')).not.toHaveCount(0);await page.clock.fastForward(13100);await page.clock.runFor(100);await expect(page.locator('.pd-cinema-layer,.pd-fx-windletter')).toHaveCount(0);
 await page.evaluate(()=>CardEffectDemo.preview('fire'));await page.clock.fastForward(3500);await page.clock.runFor(100);await page.emulateMedia({reducedMotion:'reduce'});await expect(page.locator('.pd-cinema-layer,.pd-letter-fragments,.pd-fx-windletter')).toHaveCount(0);await expect(page.locator('#pd-local')).toHaveText(headline);
});
