const {test,expect}=require('@playwright/test');const fs=require('fs'),path=require('path');test.use({serviceWorkers:'block'});
for(const width of [1280,390])test('random gauge, numbers and flag with civil scenes restore exactly '+width,async({page})=>{
 await page.setViewportSize({width,height:850});await page.setContent('<body class="mobile-details-open"><div id="painel-direito" style="position:relative;width:320px;height:600px;background:#071d2d;color:white"><svg id="pd-gauge" width="120" height="66"><path d="M10,60 A50,50 0 0 1 110,60" stroke="orange" fill="none"/></svg><div id="pd-mag" style="color:rgb(240,210,120)">6.3</div><div id="pd-flag">🇧🇷</div><div id="pd-local">Alerta de baixa umidade em São Paulo</div><button id="control">Detalhes</button></div></body>');
 for(const f of ['painel-fx.css','cinematic-card.css','card-event-typography.css'])await page.addStyleTag({content:fs.readFileSync(path.join(__dirname,'../css',f),'utf8')});
 await page.evaluate(()=>{window.__frame=null;requestAnimationFrame=fn=>(__frame=fn,1);cancelAnimationFrame=()=>__frame=null;window.CardCinemaFilm={create:()=>null,footage:()=>null};window.CardWeatherPhysics={create:()=>null};});
 for(const f of ['painel-fx.js','card-event-typography.js','card-artifact-effects.js','cinematic-card.js'])await page.addScriptTag({content:fs.readFileSync(path.join(__dirname,'../js',f),'utf8')});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));const signatures=[];
 for(const [type,extra] of [['civil',{descOnly:'Baixa Umidade'}],['civil',{descOnly:'Aviso de risco'}],['storm',{}],['flood',{}],['wind',{}],['tornado',{}],['hurricane',{}],['tsunami',{}],['fire',{}],['volcano',{detail:'Lava ativa'}],['earthquake',{mag:6.3}],['civil',{descOnly:'Baixa Umidade'}]]){
  const state=await page.evaluate(({type,extra})=>{const begin=performance.now();CinematicCard.start({type,id:'test',__cinemaDemo:true,...extra},16000);window.__begin=begin;for(const t of [1,3,5,8,12])__frame(begin+t*1000);return {actors:Array.from(document.querySelectorAll('[data-card-reaction]')).map(el=>[el.id,el.style.transform,el.style.opacity]),text:document.getElementById('pd-mag').textContent,reactions:Array.from(document.querySelectorAll('[data-event-reaction]')).map(el=>el.dataset.eventReaction)};},{type,extra});
  expect(state.actors.length).toBeGreaterThanOrEqual(2);expect(state.text).toBe('6.3');signatures.push(JSON.stringify(state.actors));
  if(extra.descOnly==='Baixa Umidade')expect(state.reactions).toContain('dry-fracture');if(extra.descOnly==='Aviso de risco')expect(state.reactions).toContain('alert-illumination');
  await page.locator('#control').click();await page.evaluate(()=>{document.getElementById('pd-mag').style.color='rgb(100,200,150)';__frame(__begin+16100);});
  await expect(page.locator('[data-card-reaction],.pd-letter-fragments,.pd-cinema-layer')).toHaveCount(0);await expect(page.locator('#pd-mag')).toHaveText('6.3');await expect(page.locator('#pd-flag')).toHaveText('🇧🇷');await expect(page.locator('#pd-mag')).toHaveCSS('color','rgb(100, 200, 150)');expect(await page.locator('#pd-gauge').evaluate(el=>el.style.transform)).toBe('');
 }
 expect(new Set(signatures).size).toBe(signatures.length);
 await page.evaluate(()=>{CinematicCard.start({type:'civil',descOnly:'Baixa Umidade',__cinemaDemo:true});__frame(performance.now()+7000);CinematicCard.stop();});await expect(page.locator('[data-card-reaction]')).toHaveCount(0);
 await page.emulateMedia({reducedMotion:'reduce'});expect(await page.evaluate(()=>CinematicCard.start({type:'civil',descOnly:'Baixa Umidade'}))).toBe(false);await expect(page.locator('[data-card-reaction],.pd-cinema-layer')).toHaveCount(0);expect(errors).toEqual([]);
});
for(const width of [1280,390])test('real civil alerts and menu use randomized card scenes '+width,async({page})=>{
 const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.setViewportSize({width,height:844});await page.route('**/*',r=>new URL(r.request().url()).hostname===new URL(base).hostname?r.continue():r.abort());await page.goto(base+'/?verify=random-card-'+Date.now());await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento&&!!window.CardArtifactEffects);await page.evaluate(()=>{pausarBuscas();clearTimeout(cycleTimeout);});await page.clock.install();await page.clock.pauseAt(await page.evaluate(()=>Date.now()+1000));
 for(const label of ['Baixa Umidade','Aviso de risco']){
  await page.evaluate(label=>{const item={id:'real-civil-'+label,type:'civil',source:'INMET',hazardNature:'warning',descOnly:label,place:label+' — São Paulo',time:Date.now(),fimTs:Date.now()+3600000,coords:[-46.63,-23.55],bandeira:'🇧🇷',sev:3};globalAlerts=[item];upsertAlert(item);showAlertDetails(item,false);clearTimeout(cycleTimeout);if(innerWidth<900)document.body.classList.add('mobile-details-open');},label);
  await expect(page.locator('.pd-cinema-layer[data-scene="civil"]')).toHaveCount(1);await page.clock.runFor(6500);await expect(page.locator('[data-card-reaction]')).not.toHaveCount(0);await expect(page.locator('#pd-local')).toContainText(label);
  await page.clock.fastForward(9800);await expect(page.locator('[data-card-reaction],.pd-cinema-layer')).toHaveCount(0);
 }
 for(const key of ['dry','civil']){await page.evaluate(key=>CardEffectDemo.preview(key),key);await page.clock.runFor(6500);await expect(page.locator('[data-card-reaction]')).not.toHaveCount(0);await page.evaluate(()=>CardEffectDemo.stop());await expect(page.locator('[data-card-reaction],.pd-cinema-layer')).toHaveCount(0);}
});
