const {test,expect}=require('@playwright/test');
test.use({serviceWorkers:'block'});
for(const width of [1280,390])test('boletim CGE na lista e texto oficial no verso '+width,async({page})=>{
 await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
 await page.setViewportSize({width,height:844});await page.goto('/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!isFirstDisplay&&!__fetchGlobalFeedsEmAndamento);
 await page.evaluate(()=>{
  const now=Date.now();const row={sourceId:'56051',title:'Chuvas isoladas na cidade',time:now-60000,displayUntil:now+3600000,summary:'Radar mostra chuvas nas zonas Norte e Leste.',description:'CGE: chuva observada nas zonas Norte e Leste. Há condições para raios nas próximas horas.'};
  const item=CgeBulletins.fromBulletin(row);globalAlerts=[item];globalEvents=[];upsertAlert(item);applyFilters();EventStore.setSelected(item.id);
 });
 if(width<900)await page.evaluate(()=>toggleMobileEventsModal(true));
 const card=page.locator('#events .event').filter({hasText:'CGE'}).first();await expect(card).toContainText('BOLETIM CGE');await expect(card).toContainText('BOLETIM OFICIAL');await expect(card).toContainText('Chuvas isoladas na cidade');
 const states=await page.evaluate(()=>({live:activeAlertingIds.has('cge-bulletin-56051'),expired:CgeBulletins.fromBulletin({sourceId:'1',time:Date.now()-7*3600000,displayUntil:Date.now()-3600000,title:'Antigo',description:'Chuva'}),link:resolveOfficialLink(EventStore.getSelected()).url}));expect(states.live).toBe(false);expect(states.expired).toBe(null);expect(states.link).toContain('noticias.jsp?id=56051');
 await card.click();await expect(page.locator('#pd-source')).toHaveText('BOLETIM CGE');expect(await page.locator('#pd-source').evaluate(el=>getComputedStyle(el,'::after').content)).toContain('PUBLICADO');await expect(page.locator('#pd-gauge-wrap')).toBeHidden();await expect(page.locator('#painel-direito > .stats-grid')).toBeHidden();await expect(page.locator('#pd-impact').locator('..')).toBeHidden();await expect(page.locator('#pd-bulletin-summary')).toContainText('Radar mostra chuvas');await expect(page.locator('#pd-bulletin-summary')).toHaveCSS('opacity','1');await expect(page.locator('#pd-more-toggle')).toHaveText('Ler boletim ↻');
 await page.screenshot({path:'/tmp/cge-front-'+width+'.png'});await page.getByRole('button',{name:'Ler boletim completo'}).click();const back=page.locator('#pd-details-verso');await expect(back).toContainText('CGE: chuva observada nas zonas Norte e Leste.');await expect(back).toContainText('não confirmam alagamentos');await expect(back.locator('h2')).toHaveText('Chuvas isoladas na cidade');await expect(back.locator('#pd-more-details')).toHaveCount(0);await expect(back.locator('details')).toHaveCount(0);await expect(back.getByRole('link',{name:'Abrir publicação no CGE'})).toHaveAttribute('href','https://www.cgesp.org/v3/noticias.jsp?id=56051');
 const textBox=await back.locator('.pd-bulletin-text').boundingBox(),backBox=await back.boundingBox();expect(textBox.y).toBeLessThan(backBox.y+backBox.height-70);
 await page.evaluate(()=>{const original=EventStore.getSelected();const revised={...original,warningDescription:'CGE: boletim revisado, texto atualizado.',detail:'Boletim revisado'};upsertAlert(revised);showAlertDetails(revised,false,true);});await expect(back).toContainText('CGE: boletim revisado');await expect(back.locator('h2')).toHaveText('Boletim revisado');
 await back.evaluate(async el=>{await Promise.all(el.getAnimations().map(a=>a.finished.catch(()=>{})));});await page.screenshot({path:'/tmp/cge-bulletin-'+width+'.png'});
 await back.getByRole('button',{name:'Voltar ao boletim'}).click();await expect(back).toHaveCount(0);await expect(page.locator('#pd-more-toggle')).toHaveText('Ler boletim ↻');
 await page.evaluate(()=>{globalEvents=[{id:'quake-after-bulletin',type:'earthquake',coords:[-90,13],time:Date.now(),mag:4,depth:12,place:'Sismo de teste'}];showEventDetails(0,false);clearTimeout(cycleTimeout);});await expect(page.locator('#pd-bulletin-summary')).toHaveCount(0);await expect(page.locator('#pd-gauge-wrap')).toBeVisible();await expect(page.locator('#pd-more-toggle')).toHaveText('Detalhes ↻');
});
