const {test,expect}=require('@playwright/test');test.use({serviceWorkers:'block',reducedMotion:'reduce'});
async function boot(page,width=1280){const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.setViewportSize({width,height:844});await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await page.goto(base+'/?verify=20261009-heavy-map',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento&&window.__mgMapReady);await page.evaluate(()=>{pausarBuscas();clearTimeout(cycleTimeout);stopWaveFront();stopFeltZone();SeismicImpact.stop();globalAlerts=[];globalEvents=[];geoFilter='all';sidebarFilter='all';soCriticos=false;});}
for(const width of [1280,390])test('seismic clipping runs in a lazy Worker and reuses the completed footprint '+width,async({page})=>{
 await page.addInitScript(()=>{const Native=window.Worker;window.__impactPosts=0;window.__impactWorkers=0;window.Worker=class extends Native{constructor(url,...args){super(url,...args);this.impact=String(url).includes('seismic-impact-worker');if(this.impact)__impactWorkers++;}postMessage(...args){if(this.impact)__impactPosts++;return super.postMessage(...args);}};});
 await boot(page,width);expect(await page.evaluate(()=>__impactWorkers)).toBe(0);
 await page.evaluate(()=>{window.__mainClips=0;const intersect=polygonClipping.intersection;polygonClipping.intersection=(...args)=>{__mainClips++;return intersect(...args);};SeismicImpact.start({id:'worker-qa',lng:139.5,lat:36,mag:6,depth:10},true);});
 await expect.poll(()=>page.evaluate(()=>__mgSeismicImpactState?.features||0),{timeout:30000}).toBeGreaterThan(10);
 const first=await page.evaluate(async()=>({data:await map.getSource('quake-impact').getData(),posts:__impactPosts,workers:__impactWorkers,clips:__mainClips}));expect(first.posts).toBe(1);expect(first.workers).toBe(1);expect(first.clips).toBe(0);
 await page.evaluate(()=>SeismicImpact.start({id:'worker-cached',lng:139.5,lat:36,mag:6,depth:10},true));await expect.poll(()=>page.evaluate(()=>__mgSeismicImpactState?.features||0)).toBeGreaterThan(10);expect(await page.evaluate(()=>__impactPosts)).toBe(1);expect(await page.evaluate(async()=>map.getSource('quake-impact').getData())).toEqual(first.data);
 await page.evaluate(()=>SeismicImpact.refresh({id:'worker-cached',lng:139.5,lat:36,mag:5.2,depth:51}));await expect.poll(()=>page.evaluate(()=>__impactPosts)).toBe(2);await expect.poll(()=>page.evaluate(()=>__mgSeismicImpactState?.features||0)).toBeGreaterThan(0);expect(await page.evaluate(()=>__mainClips)).toBe(0);
 await page.evaluate(()=>SeismicImpact.stop());expect(await page.evaluate(()=>__mgSeismicImpactState)).toBe(null);
});
for(const failure of ['constructor','script'])test('blocked Worker falls back to yielding batches and produces the same geometry '+failure,async({page})=>{
 await page.addInitScript(failure=>{const Native=window.Worker;window.Worker=function(url,...args){if(String(url).includes('seismic-impact-worker')){if(failure==='constructor')throw Error('Worker disabled in fixture');return new Native('js/worker-missing-in-fixture.js',...args);}return new Native(url,...args);};},failure);
 await boot(page);await page.evaluate(()=>{window.__uiTicks=0;window.__mainClips=0;window.__uiInterval=setInterval(()=>__uiTicks++,0);const intersect=polygonClipping.intersection;polygonClipping.intersection=(...args)=>{__mainClips++;return intersect(...args);};SeismicImpact.start({id:'fallback-qa',lng:122,lat:-10,mag:5.2,depth:51.8},true);});
 await expect.poll(()=>page.evaluate(()=>__mgSeismicImpactState?.features||0),{timeout:30000}).toBeGreaterThan(0);
 const result=await page.evaluate(async()=>{clearInterval(__uiInterval);const data=await map.getSource('quake-impact').getData(),land=(await (await fetch('assets/seismic/ne-50m-land.geojson?v=50m1')).json()).features.flatMap(f=>f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates);return {data,expected:SeismicImpactModel.geometry({lng:122,lat:-10,mag:5.2,depth:51.8},land),ticks:__uiTicks,clips:__mainClips};});// MapLibre normalizes ring winding in source.getData(). Compare coordinates in a canonical winding.
 const normalize=data=>({type:data.type,features:data.features.map(f=>({...f,geometry:{...f.geometry,coordinates:f.geometry.coordinates.map(p=>p.map(r=>{const area=r.slice(1).reduce((sum,point,i)=>sum+r[i][0]*point[1]-point[0]*r[i][1],0);return area<0?[...r].reverse():r;}))}}))});expect(normalize(result.data)).toEqual(normalize(result.expected));expect(result.ticks).toBeGreaterThan(10);expect(result.clips).toBeGreaterThanOrEqual(49);
});
for(const width of [1280,390])test('unchanged INMET inputs reuse all city and polygon data; revisions, geography, expiry and style still update '+width,async({page})=>{
 await boot(page,width);await page.evaluate(async()=>{await InmetMunicipalities.load();const rows=await (await fetch('assets/weather/br-municipalities.json?v=1')).json(),munis=InmetMunicipalities.resolve(rows.map(r=>({nome:r[1],uf:r[2]})));window.__cities=munis;globalAlerts=[{id:'inmet-cache-qa',type:'civil',hazardNature:'warning',source:'INMET',time:Date.now(),inicioTs:Date.now()-60000,fimTs:Date.now()+3600000,coords:[-46.6,-23.5],sev:2,inmetSeveridade:'Perigo',descOnly:'Baixa Umidade',place:'Baixa Umidade',municipalities:munis,municipalityLocations:munis.filter(m=>m.coords),warningGeometry:InmetAreas.geometry(JSON.stringify({type:'Polygon',coordinates:[[[-47,-24],[-46,-24],[-46,-23],[-47,-23],[-47,-24]]]}))}];layerVisibility.civil=true;layerVisibility.lightning=true;minhaPosicao={lng:-46.6,lat:-23.5};InmetMunicipalities.sync();});
 const measurements=await page.evaluate(()=>{const first=InmetMunicipalities.collection(globalAlerts),areas=InmetAreas.collection(globalAlerts);let writes=0,clips=0,checks=0;const setters=[];for(const id of ['inmet-municipalities','inmet-warning-focus','inmet-warning-areas']){const source=map.getSource(id),set=source.setData;source.setData=function(...args){writes++;return set.apply(this,args);};setters.push(()=>source.setData=set);}const clip=polygonClipping.intersection,geo=passesGeoFilter;polygonClipping.intersection=(...args)=>{clips++;return clip(...args);};passesGeoFilter=(...args)=>{checks++;return geo(...args);};for(let i=0;i<50;i++)InmetMunicipalities.sync();const state={samePoints:InmetMunicipalities.collection(globalAlerts)===first,sameAreas:InmetAreas.collection(globalAlerts)===areas,writes,clips,checks,points:__mgInmetMunicipalities.points};setters.forEach(f=>f());polygonClipping.intersection=clip;passesGeoFilter=geo;return state;});expect(measurements).toEqual({samePoints:true,sameAreas:true,writes:0,clips:0,checks:0,points:5571});
 await page.evaluate(()=>{globalAlerts[0].sev=4;globalAlerts[0].inmetSeveridade='Grande Perigo';InmetMunicipalities.sync();});expect(await page.evaluate(async()=>(await map.getSource('inmet-municipalities').getData()).features[0].properties.color)).toBe('#ef4444');
 await page.evaluate(()=>{for(const id of ['inmet-municipality-points','inmet-municipality-icons','inmet-municipality-labels','inmet-warning-fill','inmet-warning-dry','inmet-warning-outline'])if(map.getLayer(id))map.removeLayer(id);for(const id of ['inmet-municipalities','inmet-warning-focus','inmet-warning-areas'])map.removeSource(id);InmetMunicipalities.sync();});expect(await page.evaluate(async()=>(await map.getSource('inmet-municipalities').getData()).features.length)).toBe(5571);expect(await page.evaluate(async()=>(await map.getSource('inmet-warning-areas').getData()).features.length)).toBe(1);
 await page.evaluate(()=>{geoFilter='50';InmetMunicipalities.sync();});expect(await page.evaluate(()=>__mgInmetMunicipalities.points)).toBeLessThan(5571);expect(await page.evaluate(()=>__mgInmetMunicipalities.points)).toBeGreaterThan(0);
 await page.evaluate(()=>{const a=globalAlerts[0];a.warningGeometry=InmetAreas.geometry(JSON.stringify({type:'Polygon',coordinates:[[[-46.8,-23.8],[-46.5,-23.8],[-46.5,-23.3],[-46.8,-23.3],[-46.8,-23.8]]]}));a.municipalityLocations=a.municipalityLocations.slice(0,1);geoFilter='all';InmetMunicipalities.sync();});expect(await page.evaluate(()=>__mgInmetMunicipalities.points)).toBe(1);
 await page.evaluate(()=>{eventoSelecionadoId='inmet-cache-qa';InmetMunicipalities.sync();});expect(await page.evaluate(async()=>(await map.getSource('inmet-warning-focus').getData()).features.length)).toBe(1);
 await page.evaluate(()=>{globalAlerts[0].fimTs=Date.now()-1;InmetMunicipalities.sync();});expect(await page.evaluate(()=>__mgInmetMunicipalities.points)).toBe(0);expect(await page.evaluate(async()=>(await map.getSource('inmet-warning-areas').getData()).features)).toEqual([]);
});
