const {test,expect}=require('@playwright/test');test.use({serviceWorkers:'block',reducedMotion:'no-preference'});
async function boot(page){const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await page.goto(base+'/?verify=20261009-mobile-energy',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.MobileEnergyBudget&&window.__mgMapReady&&!__fetchGlobalFeedsEmAndamento);await page.evaluate(()=>{pausarBuscas();clearTimeout(cycleTimeout);stopWaveFront();stopFeltZone();SeismicCinema.stop();CinematicCard.stop();map.stop();globalEvents=[];globalAlerts=[];pendingNewCameraQuakes.clear();pendingQuakeRevisions.clear();PresentationLimits.clear();window.__lastSismoSuccess=Date.now()+86400000;});}
test('high-density mobile caps map pixels and scene budgets, retaining letters and 16-second expiry',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,serviceWorkers:'block'}),page=await context.newPage();await boot(page);
 const pixels=await page.evaluate(()=>({ratio:map.getPixelRatio(),width:map.getCanvas().width,css:map.getCanvas().clientWidth}));expect(pixels.ratio).toBe(1.25);expect(Math.abs(pixels.width-pixels.css*1.25)).toBeLessThanOrEqual(1);
 await page.evaluate(async()=>{await OptionalFeatures.effect('wind');document.body.classList.add('mobile-details-open');});await page.clock.install();await page.clock.pauseAt(await page.evaluate(()=>Date.now()+1000));await page.evaluate(()=>{const item={id:'mobile-wind',type:'wind',windKmh:140,place:'Rajada de teste',coords:[-46,-23],time:Date.now(),source:'QA'};globalAlerts=[item];showAlertDetails(item,false);clearTimeout(cycleTimeout);});
 await expect(page.locator('.pd-cinema-layer')).toHaveAttribute('data-quality','balanced');await expect(page.locator('#painel-direito')).toHaveCSS('backdrop-filter','none');expect(await page.evaluate(()=>CardEffectQuality.create(true).fps(60))).toBe(20);
 await page.clock.runFor(2000);expect(await page.locator('.pd-fx-windletter').count()).toBeGreaterThan(0);await page.clock.fastForward(15000);await expect(page.locator('.pd-cinema-layer,.pd-fx-windletter')).toHaveCount(0);await context.close();
});
for(const width of [1280,390])test('hidden rotation stays still and queued M5 wins on resume '+width,async({page})=>{
 await page.setViewportSize({width,height:844});await boot(page);await page.clock.install();await page.clock.pauseAt(await page.evaluate(()=>Date.now()+1000));
 await page.evaluate(()=>{window.__testHidden=false;Object.defineProperty(document,'hidden',{configurable:true,get:()=>__testHidden});const now=Date.now();globalEvents=[{id:'old-small',type:'earthquake',mag:2,depth:10,time:now-3600000,coords:[-65,-20],place:'Sismo antigo',source:'QA'}];window.__mgSoftCycle=true;showEventDetails(0,false);clearTimeout(cycleTimeout);stopWaveFront();stopFeltZone();map.stop();__testHidden=true;document.dispatchEvent(new Event('visibilitychange'));window.__moves=0;map.on('move',()=>__moves++);const fresh={id:'new-major',type:'earthquake',mag:5.8,depth:10,time:now,coords:[-60,-10],place:'Sismo novo maior',source:'QA'};globalEvents.push(fresh);queueNewCameraQuakes([fresh]);const alert={id:'new-weather',type:'storm',sev:3,time:now,coords:[-46,-23],place:'Alerta novo',source:'QA'};globalAlerts=[alert];NewEventPriority.queue([alert]);runAutoCycle(true);NewEventPriority.focus();});
 await page.clock.fastForward(180000);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('old-small');expect(await page.evaluate(()=>__moves)).toBe(0);expect(await page.evaluate(()=>pendingNewCameraQuakes.has('new-major')&&NewEventPriority.hasPending())).toBe(true);
 await page.evaluate(()=>{__testHidden=false;document.dispatchEvent(new Event('visibilitychange'));pausarBuscas();});await page.clock.fastForward(500);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('new-major');expect(await page.evaluate(()=>NewEventPriority.hasPending())).toBe(true);
});
test('DeX menu economy saves preference and immediately reduces desktop map and active scene budgets',async({browser})=>{
 const context=await browser.newContext({viewport:{width:1280,height:800},deviceScaleFactor:3,hasTouch:false,serviceWorkers:'block'}),page=await context.newPage();await boot(page);
 expect(await page.evaluate(()=>map.getPixelRatio())).toBe(3);
 await page.evaluate(()=>{window.__economyScene=CardEffectQuality.create(false,{deviceMemory:8,hardwareConcurrency:8});window.__economyParticles=__economyScene.track(Array.from({length:100},()=>({})));window.__firstParticle=__economyParticles[0];});
 await page.locator('#chip-menu-desktop').click();const button=page.locator('#menu-float-panel [data-energy-saving]');await expect(button).toBeVisible();await expect(button).toHaveAttribute('aria-pressed','false');await button.click();
 await expect(button).toHaveText('🔋 Economia: ligada');await expect(button).toHaveAttribute('aria-pressed','true');
 expect(await page.evaluate(()=>map.getPixelRatio())).toBe(1.25);
 expect(await page.evaluate(()=>{const resized=__economyScene.sample(0,1,16,60);return {resized,fps:__economyScene.fps(60),particles:__economyParticles.length,same:__economyParticles[0]===__firstParticle};})).toEqual({resized:true,fps:20,particles:70,same:true});
 await boot(page);expect(await page.evaluate(()=>MobileEnergyBudget.economy()&&map.getPixelRatio()===1.25)).toBe(true);
 await page.locator('#chip-menu-desktop').click();await button.click();await expect(button).toHaveAttribute('aria-pressed','false');expect(await page.evaluate(()=>map.getPixelRatio())).toBe(3);
 await boot(page);expect(await page.evaluate(()=>MobileEnergyBudget.economy())).toBe(false);await context.close();
});
test('portrait menu toggle preserves automatic mobile savings when manually switched off',async({page})=>{
 await page.setViewportSize({width:390,height:844});await boot(page);await page.evaluate(()=>MobilePortraitUI.menu());const button=page.locator('#menu-float-panel [data-energy-saving]');await expect(button).toBeVisible();await button.click();await expect(button).toHaveAttribute('aria-pressed','true');await button.click();await expect(button).toHaveAttribute('aria-pressed','false');expect(await page.evaluate(()=>MobileEnergyBudget.mobile()&&map.getPixelRatio()<=1.25)).toBe(true);
});
