const {test,expect}=require('@playwright/test');test.use({serviceWorkers:'block',reducedMotion:'reduce'});
async function boot(page,width,height=844){
 const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.setViewportSize({width,height});await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await page.goto(base+'/?verify=mobile-event-chips');await page.waitForFunction(()=>window.MobileEventChips&&window.__mgMapReady&&!__fetchGlobalFeedsEmAndamento);
 await page.evaluate(()=>{pausarBuscas();isFirstDisplay=false;PresentationLimits.clear();clearTimeout(cycleTimeout);clearTimeout(window.__mgCycleGuard);pendingNewCameraQuakes.clear();pendingQuakeRevisions.clear();stopWaveFront();stopFeltZone();SeismicCinema.stop();const now=Date.now();globalEvents=[{id:'chip-quake',type:'earthquake',mag:2.4,depth:10,coords:[-80.8,7.5],time:now-600000,place:'Panamá',source:'USGS'},{id:'chip-quake-2',type:'earthquake',mag:3.1,depth:10,coords:[-72,-13],time:now-900000,place:'Peru',source:'USGS'}];globalAlerts=[{id:'chip-tsunami',type:'tsunami',source:'PTWC',official:true,time:now,place:'Panamá',coords:[-80.8,7.5],coordinateRole:'earthquake-origin',originTime:globalEvents[0].time,originMag:2.4,hazardNature:'informational',detail:'Boletim informativo'},{id:'chip-volcano',type:'volcano',source:'NASA EONET',time:now,place:'Etna',coords:[15,38]},{id:'chip-cyclone',type:'hurricane',source:'NASA EONET',time:now,place:'Nolo',coords:[135,25]},{id:'chip-storm',type:'storm',source:'INMET',official:true,time:now,place:'Curitiba',coords:[-49,-25]}];sidebarFilter='all';lastMerged=[...globalEvents,...globalAlerts];renderSidebarList(lastMerged);MobileEventChips.update(lastMerged);});
}
for(const width of [390,540])test('mobile type chips filter only records, stay fixed on scroll, retain choice and open selected record '+width,async({page})=>{
 await boot(page,width);const before=await page.evaluate(()=>({selected:eventoSelecionadoId,filter:sidebarFilter,map:map.getCenter().toArray(),zoom:map.getZoom(),layers:JSON.stringify(layerVisibility),count:lastMerged.length}));await page.evaluate(()=>toggleMobileEventsModal(true));await expect(page.locator('#mobile-event-chips')).toBeVisible();await expect(page.locator('#events .event')).toHaveCount(6);
 const all=page.locator('#mobile-event-chips [data-event-type="all"]'),sismos=page.locator('#mobile-event-chips [data-event-type="earthquake"]'),tsunami=page.locator('#mobile-event-chips [data-event-type="tsunami"]');await sismos.click();await expect(sismos).toHaveAttribute('aria-pressed','true');await expect(page.locator('#events .event')).toHaveCount(2);await expect(page.locator('#events-count-label')).toHaveText('2 registros');await tsunami.click();await expect(page.locator('#events .event')).toHaveCount(1);await expect(page.locator('#events .event')).toHaveAttribute('data-event-id','chip-tsunami');
 expect(await page.evaluate(()=>({selected:eventoSelecionadoId,filter:sidebarFilter,map:map.getCenter().toArray(),zoom:map.getZoom(),layers:JSON.stringify(layerVisibility),count:lastMerged.length}))).toEqual(before);
 await page.evaluate(()=>{globalAlerts.push({...globalAlerts[0],id:'chip-tsunami-new',source:'NTWC',place:'Japão',coords:[142,36],originTime:Date.now()-3600000,originMag:6.2});applyFilters();});await expect(tsunami).toHaveAttribute('aria-pressed','true');await expect(page.locator('#events .event')).toHaveCount(2);await expect(page.locator('#events-count-label')).toHaveText('2 registros');await page.evaluate(()=>{globalAlerts=globalAlerts.filter(a=>a.id!=='chip-tsunami-new');applyFilters();});await page.locator('#mobile-event-chips [data-event-type="fire"]').click();await expect(page.locator('#events')).toContainText('Nenhum evento neste filtro');await expect(page.locator('#events-count-label')).toHaveText('0 registros');await tsunami.click();await page.evaluate(()=>toggleMobileEventsModal(false));await expect(page.locator('#mobile-event-chips')).toBeHidden();await page.evaluate(()=>toggleMobileEventsModal(true));await expect(tsunami).toHaveAttribute('aria-pressed','true');await expect(page.locator('#events .event')).toHaveCount(1);
 await all.click();await page.evaluate(()=>{for(let i=0;i<20;i++)lastMerged.push({...globalEvents[0],id:'scroll-'+i});renderSidebarList(lastMerged);MobileEventChips.update(lastMerged);});await page.evaluate(()=>document.getElementById('events').scrollTop=500);await expect(page.locator('#mobile-event-chips')).toBeVisible();expect(await page.evaluate(()=>{const chips=document.getElementById('mobile-event-chips'),list=document.getElementById('events');return !list.contains(chips)&&chips.parentElement.id==='sidebar-left'&&chips.getBoundingClientRect().top>=0&&chips.getBoundingClientRect().bottom<=list.getBoundingClientRect().top+1;})).toBe(true);expect(await page.evaluate(()=>document.getElementById('events').scrollTop)).toBeGreaterThan(0);await tsunami.click();expect(await page.evaluate(()=>document.getElementById('events').scrollTop)).toBe(0);
 await page.locator('#events .event').click();await expect(page.locator('#pd-local')).toContainText('Panamá');await expect.poll(()=>page.evaluate(()=>document.body.classList.contains('mobile-events-open'))).toBe(false);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('chip-tsunami');
});
test('landscape chips scroll horizontally; desktop has no extra toolbar or local filter',async({page})=>{
 await boot(page,844,390);await page.evaluate(()=>toggleMobileEventsModal(true));await expect(page.locator('#mobile-event-chips')).toBeVisible();expect(await page.evaluate(()=>{const e=document.getElementById('mobile-event-chips');return e.scrollWidth>e.clientWidth;})).toBe(true);await page.locator('#mobile-event-chips [data-event-type="tsunami"]').click();await expect(page.locator('#events .event')).toHaveCount(1);await page.setViewportSize({width:1280,height:844});await expect(page.locator('#mobile-event-chips')).toBeHidden();await expect(page.locator('#events .event')).toHaveCount(6);expect(await page.evaluate(()=>sidebarFilter)).toBe('all');
});
