const{test,expect}=require('@playwright/test');test.use({serviceWorkers:'block',reducedMotion:'reduce'});
async function boot(page,width){const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.setViewportSize({width,height:844});await page.route('**/*',r=>new URL(r.request().url()).hostname===new URL(base).hostname?r.continue():r.abort());await page.goto(base+'/?verify=new-event-priority');await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento&&window.__mgMapReady);await page.evaluate(()=>pausarBuscas());await page.clock.install();await page.clock.pauseAt(await page.evaluate(()=>Date.now()+1000));await page.evaluate(()=>{clearTimeout(cycleTimeout);pendingNewCameraQuakes.clear();pendingQuakeRevisions.clear();activeAlertingIds.clear();PresentationLimits.clear();globalEvents=[];globalAlerts=[];eventoSelecionadoId=null;EventStore.selectedId=null;isFirstDisplay=false;window.__mgRevisionProtectedUntil=0;window.__mgHoldEndsAt=0;window.__mgLiveQuakeUntil=0;window.__mgQuakeCameraPresented=new Map();});}
for(const width of [1280,390])test('small new quakes recover before historical M4.8 and all magnitudes are presented '+width,async({page})=>{
 await boot(page,width);const shown=await page.evaluate(()=>{const now=Date.now(),q=(id,mag,minutes)=>({id,type:'earthquake',mag,depth:10,time:now-minutes*60000,coords:[-65,-20],place:id,source:'EMSC'});globalEvents=[q('Historical 19h',4.8,19*60),q('Alaska M0.9',0.9,3),q('Chile M2.5',2.5,7),q('Turkey M1.2',1.2,29)];window.__mgSoftCycle=true;showEventDetails(0,false);clearTimeout(cycleTimeout);for(const q of globalEvents.slice(1))activeAlertingIds.set(q.id,now+180000);const ids=[];for(let i=0;i<3;i++){window.__mgRevisionProtectedUntil=0;window.__mgHoldEndsAt=0;window.__mgLiveQuakeUntil=0;focusNextNewCameraQuake();clearTimeout(cycleTimeout);ids.push(eventoSelecionadoId);if(i===0)globalEvents[3].time-=4*60000}return ids;});expect(shown).toEqual(['Chile M2.5','Turkey M1.2','Alaska M0.9']);await expect(page.locator('#pd-local')).toContainText('Alaska');
});
test('all alert arrivals survive M6, an older queued small quake gets its turn, then every alert before rotation',async({page})=>{
 await boot(page,1280);
 const initial=await page.evaluate(()=>{const now=Date.now();globalEvents=[{id:'M6 current',type:'earthquake',mag:6,depth:10,time:now-60000,coords:[-35,30],place:'M6 current',source:'USGS'},{id:'Small waiting',type:'earthquake',mag:0.9,depth:10,time:now-31*60000,coords:[-65,-20],place:'Small waiting',source:'USGS'}];showEventDetails(0,true);clearTimeout(cycleTimeout);queueNewCameraQuakes([globalEvents[1]]);marcarBooted('priorityQA');for(const [id,type,sev]of[['Rain alert','storm',3],['Fire alert','fire',1],['Region warning','civil',2]])upsertAlert({id,type,sev,hazardNature:'warning',time:now,coords:id==='Region warning'?null:[-46,-23],place:id,source:'INMET',expiresAt:now+3600000},{fonte:'priorityQA'});showAlertDetails(globalAlerts[0],true);return {id:eventoSelecionadoId,pending:NewEventPriority.hasPending(),quakes:pendingNewCameraQuakes.size}});expect(initial).toEqual({id:'M6 current',pending:true,quakes:1});
 const small=await page.evaluate(()=>{window.__mgRevisionProtectedUntil=0;window.__mgHoldEndsAt=0;window.__mgLiveQuakeUntil=0;runAutoCycle();clearTimeout(cycleTimeout);return eventoSelecionadoId});expect(small).toBe('Small waiting');
 const alert=await page.evaluate(()=>{window.__mgRevisionProtectedUntil=0;window.__mgHoldEndsAt=0;window.__mgLiveQuakeUntil=0;runAutoCycle();clearTimeout(cycleTimeout);return eventoSelecionadoId});expect(alert).toBe('Rain alert');
 await page.clock.fastForward(40000);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('Region warning');await expect(page.locator('#pd-local')).toContainText('Region warning');
 await page.clock.fastForward(40000);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('Fire alert');expect(await page.evaluate(()=>NewEventPriority.hasPending())).toBe(false);
 const repeated=await page.evaluate(()=>{for(const a of [...globalAlerts])upsertAlert({...a},{fonte:'priorityQA'});return NewEventPriority.hasPending()});expect(repeated).toBe(false);
});
