const{test,expect}=require('@playwright/test');test.use({serviceWorkers:'block',reducedMotion:'reduce'});
async function boot(page,width){const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.setViewportSize({width,height:844});await page.route('**/*',r=>new URL(r.request().url()).hostname===new URL(base).hostname?r.continue():r.abort());await page.goto(base+'/?verify='+Date.now());await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento&&window.__mgMapReady);await page.evaluate(()=>{pausarBuscas();clearTimeout(cycleTimeout);stopWaveFront();stopFeltZone();SeismicCinema.stop();PresentationLimits.clear();pendingNewCameraQuakes.clear();pendingQuakeRevisions.clear();activeAlertingIds.clear();isFirstDisplay=false;eventoSelecionadoId=null;EventStore.selectedId=null;window.__mgRevisionProtectedUntil=0;window.__mgLiveQuakeUntil=0;window.__mgHoldEndsAt=0;geoFilter='all';sidebarFilter='all';soCriticos=false;minMagnitude=0;});await page.clock.install();await page.clock.pauseAt(new Date(Date.now()+100));}
for(const width of [1280,390])test('every automatic kind switches by 40s even while moving; lava holds 45s '+width,async({page})=>{
 await boot(page,width);
 for(const type of ['earthquake','storm','wind','flood','hurricane','tornado','fire','civil','tsunami','volcano','lava']){
  const current=await page.evaluate(type=>{clearTimeout(cycleTimeout);PresentationLimits.clear();window.__mgRevisionProtectedUntil=0;window.__mgHoldEndsAt=0;window.__mgLiveQuakeUntil=0;window.__mgResumeRotation=false;window.__mgAutoRotation=undefined;globalEvents=[{id:'old32h',type:'earthquake',mag:4.3,depth:10,time:Date.now()-32*3600000,coords:[20,35],place:'Old quake QA',source:'EMSC'},{id:'other',type:'earthquake',mag:2.3,depth:10,time:Date.now()-33*3600000,coords:[25,36],place:'Other quake QA',source:'EMSC'}];globalAlerts=type==='earthquake'?[]:[{id:'alert-qa',type:type==='lava'?'volcano':type,time:Date.now(),coords:[22,35],place:'Automatic QA '+type,detail:type==='lava'?'New lava lake in crater':'Evento monitorado',source:'QA'}];window.__mgSoftCycle=true;if(type==='earthquake')showEventDetails(0,false);else showAlertDetails(globalAlerts[0],false);map.isMoving=()=>true;return {id:eventoSelecionadoId,cap:PresentationLimits.state()?.ms,error:window.__lastPainelDetalheError};},type);
  expect(current.error).toBeFalsy();expect(current.cap).toBe(type==='lava'?45000:40000);
  if(type==='lava'){await page.clock.fastForward(44000);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe(current.id);await page.clock.runFor(1001);}else{await page.clock.fastForward(39900);await page.clock.runFor(101);}
  expect(await page.evaluate(()=>eventoSelecionadoId)).not.toBe(current.id);
 }
});
test('historical raised revision waits behind recent M2.8 and cannot use long live hold',async({page})=>{
 await boot(page,1280);const state=await page.evaluate(()=>{globalAlerts=[];globalEvents=[{id:'old',mag:4.8,depth:10,time:Date.now()-32*3600000,coords:[22,35],place:'Old QA',source:'EMSC'},{id:'new',mag:2.8,depth:10,time:Date.now()-9*60000,coords:[25,35],place:'New QA',source:'EMSC'}];queueQuakeRevisions([{...globalEvents[0],_previousMag:4.5}]);queueNewCameraQuakes([globalEvents[1]]);focusNextNewCameraQuake();return {id:eventoSelecionadoId,cap:PresentationLimits.state(),hold:__mgHoldEndsAt-Date.now()};});expect(state.id).toBe('new');expect(state.cap).toBe(null);expect(state.hold).toBe(90000);
});
