const {test,expect}=require('@playwright/test');test.use({serviceWorkers:'block',reducedMotion:'reduce'});
for(const width of [1280,390])test('published asymmetric footprint fits land, epicenter and replicas; manual control wins '+width,async({page})=>{
 const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';let resolve;const gate=new Promise(r=>resolve=r);
 await page.setViewportSize({width,height:900});await page.route('**/*',async r=>{const u=new URL(r.request().url());if(u.pathname==='/rupture-shaking'){await gate;return r.fulfill({json:{status:'available',method:'usgs-shakemap-finite',version:'qa-finite-1',provider:'USGS ShakeMap · ruptura publicada',grid:{nx:5,ny:3,x0:-82,x1:-79,y0:7,y1:9,values:[3,5,7,5,3,3,5,7,5,3,3,5,7,5,3]}}});}return u.origin===base?r.continue():r.abort();});
 await page.goto(base);await page.waitForFunction(()=>window.SeismicFocus&&window.__mgMapReady&&!__fetchGlobalFeedsEmAndamento);
 await page.evaluate(()=>{pausarBuscas();clearTimeout(cycleTimeout);stopWaveFront();stopFeltZone();pendingNewCameraQuakes.clear();pendingQuakeRevisions.clear();globalAlerts=[];globalEvents=[{id:'rupture-qa',type:'earthquake',mag:6.6,depth:10,coords:[-80.8,7.5],time:Date.now()-3600000,place:'Panamá',source:'QA'},{id:'replica-qa',type:'earthquake',mag:4.2,depth:10,coords:[-80.6,7.8],time:Date.now()-600000,place:'Panamá',source:'QA'}];AftershockSequence.refresh();showEventDetails(0,false);clearTimeout(cycleTimeout);clearTimeout(window.__mgWaveDelayT);clearTimeout(window.__mgRadarDelayT);stopWaveFront(true);stopMapCamera();SeismicCinema.stop();fecharViradaCardAlcance();SeismicImpact.start({id:'rupture-qa',lng:-80.8,lat:7.5,mag:6.6,depth:10},true);});
 await expect.poll(()=>page.evaluate(()=>SeismicImpact.bounds('rupture-qa'))).not.toBeNull();resolve();await expect.poll(()=>page.evaluate(()=>__mgSeismicImpactState?.method)).toBe('usgs-shakemap-finite');await expect.poll(()=>page.evaluate(()=>map.getSource('quake-impact').serialize().data.features.every(f=>f.properties.official===true))).toBe(true);
 const fit=await page.evaluate(()=>{const c={id:'rupture-qa',lng:-80.8,lat:7.5,mag:6.6,depth:10},f=SeismicFocus.frame(c);return {f,bounds:SeismicImpact.bounds(c.id),points:AftershockSequence.framePoints(c.id)};});for(const [x,y]of fit.points){expect(x).toBeGreaterThanOrEqual(fit.f.bounds[0]);expect(x).toBeLessThanOrEqual(fit.f.bounds[2]);expect(y).toBeGreaterThanOrEqual(fit.f.bounds[1]);expect(y).toBeLessThanOrEqual(fit.f.bounds[3]);}expect(fit.f.bounds[3]).toBeLessThanOrEqual(9);
 await page.evaluate(()=>{map.fire('dragstart',{originalEvent:{}});map.jumpTo({center:[10,20],zoom:5});SeismicFocus.ready({id:'rupture-qa',lng:-80.8,lat:7.5,mag:6.6,depth:10});});expect(await page.evaluate(()=>map.getCenter().toArray())).toEqual([10,20]);
 await page.evaluate(()=>{SeismicImpact.stop();showEventDetails(1,false);clearTimeout(cycleTimeout);clearTimeout(window.__mgWaveDelayT);clearTimeout(window.__mgRadarDelayT);});expect(await page.evaluate(()=>SeismicImpact.bounds('rupture-qa'))).toBeNull();
});
test('a late rupture response cannot replace another selected event',async({page})=>{
 const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';let resolve;const gate=new Promise(r=>resolve=r);await page.route('**/*',async r=>{const u=new URL(r.request().url());if(u.pathname==='/rupture-shaking'){await gate;try{await r.fulfill({json:{status:'available',method:'usgs-shakemap-finite',version:'late-qa',grid:{nx:2,ny:2,x0:-82,x1:-79,y0:7,y1:9,values:[5,5,5,5]}}});}catch{}return;}return u.origin===base?r.continue():r.abort();});await page.goto(base);await page.waitForFunction(()=>window.SeismicFocus&&window.__mgMapReady&&!__fetchGlobalFeedsEmAndamento);
 await page.evaluate(()=>{pausarBuscas();clearTimeout(cycleTimeout);stopWaveFront();stopFeltZone();globalEvents=[{id:'old-rupture',type:'earthquake',mag:6.6,depth:10,coords:[-80.8,7.5],time:Date.now()-3600000,place:'Panamá',source:'QA'},{id:'new-other',type:'earthquake',mag:3,depth:10,coords:[30,38],time:Date.now(),place:'Turquia',source:'QA'}];globalAlerts=[];showEventDetails(0,false);clearTimeout(cycleTimeout);clearTimeout(window.__mgWaveDelayT);clearTimeout(window.__mgRadarDelayT);SeismicImpact.start({id:'old-rupture',lng:-80.8,lat:7.5,mag:6.6,depth:10},true);});await expect.poll(()=>page.evaluate(()=>__mgSeismicImpactState?.id)).toBe('old-rupture');await page.evaluate(()=>{showEventDetails(1,false);clearTimeout(cycleTimeout);clearTimeout(window.__mgWaveDelayT);clearTimeout(window.__mgRadarDelayT);stopWaveFront();stopFeltZone();stopMapCamera();map.jumpTo({center:[30,38],zoom:6});});resolve();await page.evaluate(async()=>{await new Promise(r=>setTimeout(r,300));});expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('new-other');expect(await page.evaluate(()=>__mgSeismicImpactState?.id||null)).not.toBe('old-rupture');expect(await page.evaluate(()=>map.getCenter().toArray())).toEqual([30,38]);
});
