const {test,expect}=require('@playwright/test');test.use({serviceWorkers:'block',reducedMotion:'no-preference'});
for(const width of [1280,390])test('camera follows red then holds painted area; blue only last 6s; final area 10s '+width,async({page})=>{
 test.setTimeout(180000);const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await page.setViewportSize({width,height:844});await page.goto(base+'/?verify=red-camera-focus',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento&&GlobalQuakeTravel.status()==='ready');
 await page.evaluate(()=>{pausarBuscas();pendingNewCameraQuakes.clear();pendingQuakeRevisions.clear();clearTimeout(cycleTimeout);stopWaveFront();stopFeltZone();SeismicCinema.stop();});await page.clock.install();await page.clock.pauseAt(await page.evaluate(()=>Date.now()+1000));await page.evaluate(()=>{maplibregl.setNow(performance.now());window.requestAnimationFrame=cb=>setTimeout(()=>{maplibregl.setNow(performance.now());cb(performance.now());},100);window.cancelAnimationFrame=id=>clearTimeout(id);});
 const expected=await page.evaluate(()=>{
  const mag=5.1,depth=10,lng=125.2,lat=1.1,felt=SeismicImpact.extent(mag,depth),end=waveDisplaySeconds(mag,depth);let lo=0,hi=end;for(let i=0;i<40;i++){const mid=(lo+hi)/2;if((GlobalQuakeTravel.radius('s',depth,mid)||0)<felt)lo=mid;else hi=mid;}
  const item={id:'tour-qa',type:'earthquake',mag,depth,coords:[lng,lat],time:Date.now()-(hi-3)*1000,place:'Bitung QA',source:'QA'};globalEvents=[item];globalAlerts=[];showEventDetails(0,false);clearTimeout(cycleTimeout);clearTimeout(window.__mgWaveDelayT);clearTimeout(window.__mgRadarDelayT);stopMapCamera();window.__tourSchedules=[];window.scheduleNextAutoCycle=ms=>__tourSchedules.push(ms);map.jumpTo({center:centroCompensado(lng,lat,7),zoom:7});startWaveFront(lng,lat,mag,depth,item.time,{id:item.id,mode:'live',chaseCam:true,protectUntilEnd:true,returnToEpicenter:true});return {end,origin:item.time,felt,target:zoomParaAreaPintada(lng,lat,Math.max(10,SeismicImpactModel.extent(mag,depth,2.1)))};
 });await expect.poll(()=>page.evaluate(()=>__mgSeismicImpactState?.features||0)).toBeGreaterThan(0);
 await page.clock.runFor(1500);expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).toBe('s');await page.clock.runFor(5000);expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).toBe('impact');expect(await page.evaluate(()=>__mgSeismicImpactState.stage)).toBe('impact');
 await page.clock.runFor(10000);expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).toBe('impact');expect(await page.evaluate(()=>map.getZoom())).toBeCloseTo(expected.target,1);
 await page.clock.fastForward(expected.origin+(expected.end-7)*1000-await page.evaluate(()=>Date.now()));await page.clock.runFor(500);expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).toBe('impact');
 await page.clock.runFor(1000);expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).toBe('p-final');await page.clock.runFor(3500);expect(await page.evaluate(()=>map.getZoom())).toBeLessThan(expected.target);expect(await page.evaluate(()=>__mgSeismicImpactState.stage)).toBe('impact');
 await page.clock.fastForward(expected.origin+expected.end*1000-await page.evaluate(()=>Date.now())+100);await page.clock.runFor(3700);await expect.poll(()=>page.evaluate(()=>Math.abs(map.getZoom()-zoomParaAreaPintada(125.2,1.1,Math.max(10,SeismicImpactModel.extent(5.1,10,2.1))))),{timeout:8000}).toBeLessThan(.05);const final=await page.evaluate(()=>({...__mgWaveFrontState,zoom:map.getZoom(),now:Date.now(),until:__mgRevisionProtectedUntil,target:zoomParaAreaPintada(125.2,1.1,Math.max(10,SeismicImpactModel.extent(5.1,10,2.1)))}));expect(final.stage).toBe('returning');expect(final.cameraPhase).toBe('impact-final');expect(final.zoom).toBeCloseTo(final.target,1);expect(final.until-final.now).toBeGreaterThan(9500);expect(final.until-final.now).toBeLessThanOrEqual(10000);expect(await page.evaluate(()=>map.getFilter('quake-impact-fill')??null)).toBeNull();await page.clock.fastForward(final.until-final.now+30);expect(await page.evaluate(()=>__mgWaveFrontState)).toBeNull();expect(await page.evaluate(()=>__mgSeismicImpactState.features)).toBeGreaterThan(0);
});
