const {test,expect}=require('@playwright/test');test.use({serviceWorkers:'block',reducedMotion:'no-preference'});
for(const width of [1280,390])test('camera follows red then holds painted area; blue only last 6s; final area 10s '+width,async({page})=>{
 test.setTimeout(180000);const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await page.setViewportSize({width,height:844});await page.goto(base+'/?verify=red-camera-focus',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento&&GlobalQuakeTravel.status()==='ready');
 await page.evaluate(()=>{pausarBuscas();pendingNewCameraQuakes.clear();pendingQuakeRevisions.clear();clearTimeout(cycleTimeout);stopWaveFront();stopFeltZone();SeismicCinema.stop();});await page.clock.install();await page.clock.pauseAt(await page.evaluate(()=>Date.now()+1000));await page.evaluate(()=>{maplibregl.setNow(performance.now());window.requestAnimationFrame=cb=>setTimeout(()=>{maplibregl.setNow(performance.now());cb(performance.now());},100);window.cancelAnimationFrame=id=>clearTimeout(id);});
 const expected=await page.evaluate(()=>{
  const mag=5.1,depth=10,lng=125.2,lat=1.1,felt=SeismicImpact.extent(mag,depth),end=waveDisplaySeconds(mag,depth);let lo=0,hi=end;for(let i=0;i<40;i++){const mid=(lo+hi)/2;if((GlobalQuakeTravel.radius('s',depth,mid)||0)<felt)lo=mid;else hi=mid;}
  const item={id:'tour-qa',type:'earthquake',mag,depth,coords:[lng,lat],time:Date.now()-(hi-3)*1000,place:'Bitung QA',source:'QA'};globalEvents=[item];globalAlerts=[];showEventDetails(0,false);clearTimeout(cycleTimeout);clearTimeout(window.__mgWaveDelayT);clearTimeout(window.__mgRadarDelayT);stopMapCamera();window.__tourSchedules=[];window.scheduleNextAutoCycle=ms=>__tourSchedules.push(ms);map.jumpTo({center:centroCompensado(lng,lat,7),zoom:7});startWaveFront(lng,lat,mag,depth,item.time,{id:item.id,mode:'live',chaseCam:true,protectUntilEnd:true,returnToEpicenter:true});return {end,origin:item.time,felt,target:zoomParaAreaPintada(lng,lat,Math.max(10,SeismicImpactModel.extent(mag,depth,2.1)))};
 });await expect.poll(()=>page.evaluate(()=>__mgSeismicImpactState?.features||0)).toBeGreaterThan(0);
 expected.target=await page.evaluate(()=>SeismicFocus.frame({id:'tour-qa',lng:125.2,lat:1.1,mag:5.1,depth:10}).zoom);await page.clock.runFor(1500);expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).toBe('s');await page.clock.runFor(5000);expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).toBe('impact');expect(await page.evaluate(()=>__mgSeismicImpactState.stage)).toBe('impact');
 await page.clock.runFor(10000);expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).toBe('impact');expect(await page.evaluate(()=>map.getZoom())).toBeCloseTo(expected.target,1);
 await page.clock.fastForward(expected.origin+(expected.end-7)*1000-await page.evaluate(()=>Date.now()));await page.clock.runFor(500);expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).toBe('impact');
 await page.clock.runFor(1000);expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).toBe('p-final');await page.clock.runFor(3500);expect(await page.evaluate(()=>map.getZoom())).toBeLessThan(expected.target);expect(await page.evaluate(()=>__mgSeismicImpactState.stage)).toBe('impact');
 await page.clock.fastForward(expected.origin+expected.end*1000-await page.evaluate(()=>Date.now())+100);await page.clock.runFor(3700);await expect.poll(()=>page.evaluate(()=>Math.abs(map.getZoom()-SeismicFocus.frame({id:'tour-qa',lng:125.2,lat:1.1,mag:5.1,depth:10}).zoom)),{timeout:8000}).toBeLessThan(.05);const final=await page.evaluate(()=>({...__mgWaveFrontState,zoom:map.getZoom(),now:Date.now(),until:__mgRevisionProtectedUntil,target:SeismicFocus.frame({id:'tour-qa',lng:125.2,lat:1.1,mag:5.1,depth:10}).zoom}));expect(final.stage).toBe('returning');expect(final.cameraPhase).toBe('impact-final');expect(final.zoom).toBeCloseTo(final.target,1);expect(final.until-final.now).toBeGreaterThan(9500);expect(final.until-final.now).toBeLessThanOrEqual(10000);expect(await page.evaluate(()=>map.getFilter('quake-impact-fill')??null)).toBeNull();await expect(page.locator('#pd-seismic-final-summary')).toBeVisible();await expect(page.locator('#pd-seismic-final-summary')).not.toContainText('População potencialmente');await page.evaluate(()=>{const main=globalEvents[0];globalEvents.push({...main,id:'final-replica',mag:4.1,time:main.time+180000,coords:[main.coords[0]+.05,main.coords[1]+.05]});AftershockSequence.refresh();});await expect(page.locator('#pd-seismic-final-summary')).toContainText('Possíveis réplicas');await expect(page.locator('#pd-seismic-final-summary')).toContainText('maior M4,1');await page.clock.fastForward(final.until-final.now+30);expect(await page.evaluate(()=>__mgWaveFrontState)).toBeNull();expect(await page.evaluate(()=>__mgSeismicImpactState.features)).toBeGreaterThan(0);
});

for(const width of [1280,390])test('small quake holds epicenter, blue last 10s, returns then holds 10s '+width,async({page})=>{
 test.setTimeout(180000);const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await page.setViewportSize({width,height:844});await page.goto(base+'/?verify=small-epicenter-camera',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento&&GlobalQuakeTravel.status()==='ready');
 await page.evaluate(()=>{pausarBuscas();pendingNewCameraQuakes.clear();pendingQuakeRevisions.clear();clearTimeout(cycleTimeout);stopWaveFront();stopFeltZone();SeismicCinema.stop();});await page.clock.install();await page.clock.pauseAt(await page.evaluate(()=>Date.now()+1000));await page.evaluate(()=>{maplibregl.setNow(performance.now());window.requestAnimationFrame=cb=>setTimeout(()=>{maplibregl.setNow(performance.now());cb(performance.now());},100);window.cancelAnimationFrame=id=>clearTimeout(id);});
 const expected=await page.evaluate(()=>{
  const mag=4.2,depth=10,lng=-80.77,lat=7.59,end=Math.min(GlobalQuakeTravel.endTime('p',depth),waveDisplaySeconds(mag,depth)),origin=Date.now(),zoom=8;
  const item={id:'small-tour-qa',type:'earthquake',mag,depth,coords:[lng,lat],time:origin,place:'Panamá QA',source:'QA'};globalEvents=[item];globalAlerts=[];showEventDetails(0,false);clearTimeout(cycleTimeout);clearTimeout(window.__mgWaveDelayT);clearTimeout(window.__mgRadarDelayT);stopMapCamera();stopWaveFront();stopFeltZone();window.__tourSchedules=[];window.scheduleNextAutoCycle=ms=>__tourSchedules.push(ms);map.jumpTo({center:centroCompensado(lng,lat,zoom),zoom});startWaveFront(lng,lat,mag,depth,origin,{id:item.id,mode:'live',chaseCam:true,protectUntilEnd:true,epicenterFirst:true,epicenterZoom:zoom});return {end,origin,zoom};
 });
 await page.clock.runFor(5000);expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).toBe('epicenter');expect(await page.evaluate(()=>map.getZoom())).toBeCloseTo(expected.zoom,2);
 await page.clock.runFor(10000);await page.evaluate(()=>{window.__steadyJumps=0;const jump=map.jumpTo.bind(map);map.jumpTo=(...args)=>{__steadyJumps++;return jump(...args);};});await page.clock.runFor(3000);expect(await page.evaluate(()=>__steadyJumps)).toBe(0);
 await page.evaluate(()=>{const item=globalEvents[0];item.coords=[item.coords[0]+.02,item.coords[1]+.02];refreshWaveFront(item);});await page.clock.runFor(4000);expect(await page.evaluate(()=>__steadyJumps)).toBeGreaterThan(0);expect(await page.evaluate(()=>__mgWaveFrontState.originTime)).toBe(expected.origin);
 await page.evaluate(()=>{window.exposicaoPopulacionalDoEvento=()=>({status:'available',method:'pager',partial:true,ranges:[{population:12345},{population:1000},{population:100}]});});
 await page.clock.fastForward(expected.origin+(expected.end-11)*1000-await page.evaluate(()=>Date.now()));await page.clock.runFor(500);expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).toBe('epicenter');expect(await page.evaluate(()=>map.getZoom())).toBeCloseTo(expected.zoom,2);
 await page.clock.runFor(1000);expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).toBe('p-final');await page.clock.runFor(4000);expect(await page.evaluate(()=>map.getZoom())).toBeLessThan(expected.zoom-1);
 await page.clock.fastForward(expected.origin+expected.end*1000-await page.evaluate(()=>Date.now())+100);await page.clock.runFor(3700);expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).toBe('epicenter-final');expect(await page.evaluate(()=>map.getZoom())).toBeCloseTo(expected.zoom,2);await expect(page.locator('#pd-seismic-final-summary')).toBeVisible();await expect(page.locator('#pd-seismic-final-summary')).toContainText('12.345 pessoas');await expect(page.locator('#pd-seismic-final-summary')).toContainText('cobertura parcial');await expect(page.locator('#pd-seismic-final-summary')).toContainText('Intensidade estimada');const recap=await page.locator('#pd-seismic-final-summary').boundingBox();expect(recap.y+recap.height).toBeLessThanOrEqual(844);const remaining=await page.evaluate(()=>__mgRevisionProtectedUntil-Date.now());expect(remaining).toBeGreaterThan(9400);expect(remaining).toBeLessThanOrEqual(10000);await page.clock.runFor(9000);expect(await page.evaluate(()=>waveFrontAtivo)).toBe(true);await page.clock.runFor(1200);expect(await page.evaluate(()=>__mgWaveFrontState)).toBeNull();expect(await page.evaluate(()=>__tourSchedules.at(-1))).toBe(13520);await expect(page.locator('#pd-seismic-final-summary')).toHaveCount(0);
});
