const{test,expect}=require('@playwright/test');test.use({serviceWorkers:'block',reducedMotion:'reduce'});
async function boot(page,width){const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.setViewportSize({width,height:844});await page.route('**/*',r=>new URL(r.request().url()).hostname===new URL(base).hostname?r.continue():r.abort());await page.goto(base+'/?verify='+Date.now());await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento&&GlobalQuakeTravel?.status()==='ready');await page.evaluate(()=>{pausarBuscas();pendingNewCameraQuakes.clear();pendingQuakeRevisions.clear();activeAlertingIds.clear();clearTimeout(cycleTimeout);stopWaveFront();stopFeltZone();SeismicCinema.stop();isFirstDisplay=false;});}
for(const width of [1280,390])test('M5+ land intensity follows S, returns to the affected area for ten seconds and yields to larger quake '+width,async({page})=>{
 test.setTimeout(90000);await boot(page,width);await page.clock.install();await page.clock.pauseAt(new Date(Date.now()+100));
 const end=await page.evaluate(()=>{const id='impact-qa',mag=6,depth=10,end=waveDisplaySeconds(mag,depth);globalEvents=[{id,type:'earthquake',mag,depth,time:Date.now()-(end-1)*1000,coords:[139.5,36],place:'Japan QA',source:'QA'}];eventoSelecionadoId=id;window.__mgRevisionProtectedId=id;window.__mgRevisionProtectedUntil=Date.now()+90000;window.__mgHoldEndsAt=__mgRevisionProtectedUntil;map.jumpTo({center:[139.5,36],zoom:2});startWaveFront(139.5,36,mag,depth,globalEvents[0].time,{id,mode:'live',protectUntilEnd:true,returnToEpicenter:true,epicenterZoom:7});return end;});
 await expect.poll(()=>page.evaluate(()=>window.__mgSeismicImpactState?.features||0)).toBeGreaterThan(0);await expect(page.locator('.seismic-impact-status')).toContainText('estimada');
 const source=await page.evaluate(async()=>{const data=await map.getSource('quake-impact').getData();return {count:data.features.length,colors:new Set(data.features.map(f=>f.properties.color)).size,pga:data.features.map(f=>f.properties.pga)};});expect(source.count).toBeGreaterThan(10);expect(source.colors).toBeGreaterThan(10);
 await page.clock.runFor(2000);
 expect(await page.evaluate(()=>__mgWaveFrontState.stage)).toBe('returning');expect(await page.evaluate(()=>map.getZoom())).toBeCloseTo(await page.evaluate(()=>zoomParaAreaPintada(139.5,36,SeismicImpact.extent(6,10))),1);expect(await page.evaluate(()=>map.getPaintProperty('wave-front-p-line','line-opacity'))).toBe(0);expect(await page.evaluate(()=>__mgSeismicImpactState.stage)).toBe('impact');
 await page.clock.runFor(100);if(width===390){const legend=await page.locator('.seismic-impact-status').boundingBox(),ticker=await page.locator('#latest-event-ticker').boundingBox();expect(legend.y).toBeGreaterThan(ticker.y+ticker.height);}await page.screenshot({path:'/tmp/seismic-impact-'+width+'.png'});
 await page.clock.fastForward(10100);expect(await page.evaluate(()=>__mgWaveFrontState)).toBe(null);
 await page.evaluate(()=>{globalEvents.push({id:'larger-impact-qa',type:'earthquake',mag:7,depth:10,time:Date.now(),coords:[140,36],place:'Larger QA',source:'QA'});queueNewCameraQuakes([globalEvents[1]]);focusNextNewCameraQuake();});await expect(page.locator('#pd-local')).toContainText('Larger QA');expect(await page.evaluate(()=>__mgSeismicImpactState)).toBe(null);
});
test('M5 delayed arrivals paint land without fake waves; automatic rotation keeps its radar',async({page})=>{
 await boot(page,1280);await page.evaluate(()=>{const id='late-impact-qa';globalEvents=[{id,type:'earthquake',mag:5.2,depth:51.8,time:Date.now()-20*60000,coords:[122,-10],place:'Savu QA',source:'QA'}];eventoSelecionadoId=id;startWaveFront(122,-10,5.2,51.8,globalEvents[0].time,{id,mode:'live',returnToEpicenter:true});});await page.waitForFunction(()=>window.__mgSeismicImpactState?.features>0);expect(await page.evaluate(()=>__mgWaveFrontState)).toBe(null);expect(await page.evaluate(()=>__mgSeismicImpactState.stage)).toBe('impact');await expect(page.locator('.felt-zone-status')).toHaveCount(0);
 await page.evaluate(()=>startFeltZone(122,-10,5.2,51.8,'late-impact-qa'));expect(await page.evaluate(()=>__mgSeismicImpactState)).toBe(null);await expect(page.locator('.felt-zone-status')).toHaveCount(1);
});
test('normal motion camera opens, returns smoothly, and a larger arrival interrupts the return',async({page})=>{
 test.setTimeout(120000);await page.emulateMedia({reducedMotion:'no-preference'});await boot(page,1280);await page.clock.install();await page.clock.pauseAt(new Date(Date.now()+100));
 await page.evaluate(()=>{const id='return-motion-qa',mag=5.2,depth=12,end=waveDisplaySeconds(mag,depth);globalEvents=[{id,type:'earthquake',mag,depth,time:Date.now()-(end-1)*1000,coords:[178,-18],place:'Fiji QA',source:'QA'}];eventoSelecionadoId=id;window.__mgRevisionProtectedId=id;window.__mgRevisionProtectedUntil=Date.now()+90000;window.__mgHoldEndsAt=__mgRevisionProtectedUntil;window.__returnCamera=[];const ease=map.easeTo.bind(map);map.easeTo=options=>{__returnCamera.push({duration:options.duration,zoom:options.zoom});return ease(options);};map.jumpTo({center:[178,-18],zoom:1.5});startWaveFront(178,-18,mag,depth,globalEvents[0].time,{id,mode:'live',chaseCam:true,protectUntilEnd:true,returnToEpicenter:true,epicenterZoom:7});});
 await expect.poll(()=>page.evaluate(()=>window.__mgSeismicImpactState?.features||0)).toBeGreaterThan(0);await page.clock.runFor(1400);expect(await page.evaluate(()=>__mgWaveFrontState.stage)).toBe('returning');await page.clock.runFor(700);
 expect(await page.evaluate(()=>__mgWaveFrontState.stage)).toBe('returning');const z=await page.evaluate(()=>map.getZoom());expect(z).toBeGreaterThan(1.5);expect(z).toBeLessThanOrEqual(7);expect(await page.evaluate(()=>__returnCamera.some(c=>c.duration===3500&&c.zoom>1.5&&c.zoom<7))).toBe(true);
 await page.evaluate(()=>{globalEvents.push({id:'return-bigger-qa',type:'earthquake',mag:6,depth:10,time:Date.now(),coords:[140,36],place:'Bigger return QA',source:'QA'});queueNewCameraQuakes([globalEvents[1]]);focusNextNewCameraQuake();clearTimeout(window.__mgWaveDelayT);clearTimeout(window.__mgRadarDelayT);});expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('return-bigger-qa');expect(await page.evaluate(()=>window.__mgSeismicImpactState)).toBe(null);await page.clock.fastForward(19000);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('return-bigger-qa');
});
