const {test,expect}=require('@playwright/test');test.use({serviceWorkers:'block',reducedMotion:'reduce'});
for(const width of [1280,390])test('source health shares menu and header, separates valid/failure times and honors category intervals '+width,async({page})=>{
 const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.setViewportSize({width,height:800});await page.route('**/*',r=>new URL(r.request().url()).hostname===new URL(base).hostname?r.continue():r.abort());await page.goto(base+'/?source-health='+Date.now());await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento&&window.__mgMapReady);
 await page.evaluate(()=>{pausarBuscas();const names=['USGS','USGS-RT','OVSICORI','MARN-SV','GEOFON','FUNVISIS','JMA','IGP','OSC-BOL','BMKG','GEONET','USP','CSN-Chile','SSN-Mexico','EMSC'];for(const n of names)MonitorFreshness.record(n,true);window.__lastSismoSuccess=Date.now();window.__sismoUsingCache=false;MonitorFreshness.endQuakes();setSource('IGP','off',0,'HTTP 503');setSource('NHC','ok');MonitorFreshness.recordStatus('NHC','ok','',0,Date.now()-10*60000);setSource('ANA','paused',null,'Integração pausada');window.__uxShow('sources');});
 const dialog=page.locator('#mg-fresh-dialog');await expect(dialog).toBeVisible();await expect(dialog.locator('h2')).toHaveText('Situação das fontes');await expect(dialog.locator('.mg-fresh-missing').filter({hasText:'Fontes sísmicas'})).toContainText('IGP');
 const igp=dialog.locator('[data-source="IGP"]');await expect(igp).toHaveAttribute('data-state','error');await expect(igp).toContainText('Última tentativa:');await expect(igp).toContainText('Última consulta válida:');await expect(igp).toContainText('dados anteriores');await igp.locator('summary').click();await expect(igp).toContainText('HTTP 503');
 await expect(dialog.locator('[data-source="NHC"]')).toHaveAttribute('data-state','fresh');await expect(dialog.locator('[data-source="NHC"]')).toContainText('1 hora');await expect(dialog.locator('[data-source="ANA"]')).toHaveAttribute('data-state','paused');
 await page.evaluate(()=>MonitorFreshness.recordStatus('USGS','ok'));await expect(igp.locator('details')).toHaveAttribute('open','');expect(await dialog.evaluate(d=>d.scrollWidth<=d.clientWidth+1)).toBe(true);
 await dialog.locator('.mg-fresh-close').click();await page.locator('#ao-vivo-badge').click();await expect(dialog).toBeVisible();await expect(page.locator('#ao-vivo-badge')).toHaveAttribute('data-freshness','partial');
 await page.evaluate(()=>setSource('IGP','ok'));await expect(igp).toHaveAttribute('data-state','fresh');await expect(page.locator('#ao-vivo-badge')).toHaveAttribute('data-freshness','fresh');
});

test('partial official tsunami products remain partial while successful centers stay available',async({page})=>{
 const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.pathname==='/tsunami-alerts')return r.fulfill({json:{ok:true,sources:[{source:'PTWC',feedKey:'PTWC-a',ok:true},{source:'PTWC',feedKey:'PTWC-b',ok:false,error:'HTTP 503'},{source:'NTWC',ok:true}],items:[]}});return u.hostname===new URL(base).hostname?r.continue():r.abort();});await page.goto(base+'/?tsunami-health='+Date.now());await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento&&window.__mgMapReady);const state=await page.evaluate(async()=>{pausarBuscas();await fetchOfficialTsunamiAlerts();return {pt:MonitorFreshness.snapshot('PTWC boletins'),nt:MonitorFreshness.snapshot('NTWC boletins')};});expect(state.pt.state).toBe('partial');expect(state.pt.error).toContain('HTTP 503');expect(state.nt.state).toBe('fresh');
});
