const {test,expect}=require('@playwright/test');
test.use({serviceWorkers:'block'});
for(const width of [1280,390])test('relâmpagos ramificados, informação legível e troca de evento '+width,async({page})=>{
 await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.setViewportSize({width,height:844});await page.goto('/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento);
 await page.evaluate(()=>{const item={id:'storm-observed',type:'storm',source:'NOAA METAR',hazardNature:'observed',detail:'Trovoada reportada no aeródromo',place:'São Paulo — Brasil',bandeira:'🇧🇷',coords:[-46.63,-23.55],time:Date.now()};globalAlerts=[item];upsertAlert(item);showAlertDetails(item,false);clearTimeout(cycleTimeout);});
 await expect(page.locator('#painel-direito')).toHaveAttribute('data-lightning','on');await expect(page.locator('#pd-mag')).not.toContainText('⚡');await expect(page.locator('#pd-mag svg[role="img"]')).toHaveAttribute('aria-label',/relâmpagos/);await expect(page.locator('.pd-fx-bolt polygon')).toHaveCount(0);await expect(page.locator('.pd-fx-bolt .pd-bolt-branch')).toHaveCount(8);await expect(page.locator('#pd-local')).toContainText('São Paulo');
 const before=await page.locator('.pd-fx-bolt-1 .pd-bolt-core').getAttribute('d');await page.evaluate(()=>showAlertDetails(EventStore.getSelected(),false,true));expect(await page.locator('.pd-fx-bolt-1 .pd-bolt-core').getAttribute('d')).toBe(before);
 // Freeze a discharge peak for visual inspection, without changing its geometry or layout.
 await page.evaluate(()=>{for(const el of document.querySelectorAll('.pd-fx-bolt,#lightning-flash'))for(const a of el.getAnimations()){a.pause();a.currentTime=610;}});await expect(page.locator('.pd-fx-bolt-1')).toHaveCSS('opacity','0.95');await expect(page.locator('.pd-fx-bolt-1')).toHaveCSS('pointer-events','none');await expect(page.locator('#lightning-flash')).toHaveCSS('opacity','0.22');await page.screenshot({path:'/tmp/storm-lightning-'+width+'.png'});
 await page.evaluate(()=>{globalEvents=[{id:'after-storm',type:'earthquake',place:'Sismo de teste',coords:[-90,13],time:Date.now(),depth:10,mag:4.8}];showEventDetails(0,false);clearTimeout(cycleTimeout);});await expect(page.locator('#painel-direito')).not.toHaveClass(/pd-fx-storm/);await expect(page.locator('#pd-mag svg')).toHaveCount(0);await expect(page.locator('.pd-fx-bolt-1')).toHaveCSS('opacity','0');
});
test('aviso de chuva não ganha relâmpagos, e movimento reduzido não pisca',async({page})=>{
 await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.goto('/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento);
 await page.evaluate(()=>{const item={id:'rain-warning',type:'storm',hazardNature:'warning',warningEvent:'Heavy Rainfall Warning',detail:'Aviso de chuva intensa',source:'ECCC',place:'Região de teste',time:Date.now(),coords:[-90,50]};globalAlerts=[item];upsertAlert(item);showAlertDetails(item,false);clearTimeout(cycleTimeout);});await expect(page.locator('#painel-direito')).toHaveAttribute('data-lightning','off');await expect(page.locator('.pd-fx-bolt-1')).toHaveCSS('display','none');await expect(page.locator('#lightning-flash')).toBeHidden();
 await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>{const item={...EventStore.getSelected(),id:'thunder-warning',warningEvent:'Severe Thunderstorm Warning'};upsertAlert(item);showAlertDetails(item,false);clearTimeout(cycleTimeout);});await expect(page.locator('#painel-direito')).toHaveAttribute('data-lightning','on');await expect(page.locator('.pd-fx-bolt-1')).toHaveCSS('animation-name','none');await expect(page.locator('#lightning-flash')).toHaveCSS('animation-name','none');
});
