const {test,expect}=require('@playwright/test');test.use({serviceWorkers:'block',reducedMotion:'no-preference'});
async function boot(page,width=1280){
 const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.setViewportSize({width,height:900});await page.route('**/*',r=>new URL(r.request().url()).origin===base||(process.env.TSUNAMI_VISUAL_SATELLITE==='1'&&r.request().url().includes('server.arcgisonline.com'))?r.continue():r.abort());await page.goto(base+'/?verify=linked-tsunami-tour',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__mgMapReady&&!__fetchGlobalFeedsEmAndamento&&GlobalQuakeTravel.status()==='ready'&&window.TsunamiPresentation);
 await page.evaluate(()=>{pausarBuscas();PeriodicScheduler.cancel('correlation');clearTimeout(cycleTimeout);pendingNewCameraQuakes.clear();pendingQuakeRevisions.clear();NewEventPriority.clear?.();stopWaveFront();stopFeltZone();SeismicCinema.stop();globalAlerts=[];globalEvents=[];PresentationLimits.clear();});
 await page.clock.install();await page.clock.pauseAt(await page.evaluate(()=>Date.now()+1000));await page.evaluate(()=>{window.requestAnimationFrame=cb=>setTimeout(()=>cb(performance.now()),100);window.cancelAnimationFrame=id=>clearTimeout(id);window.__tourFlights=[];const fly=map.flyTo.bind(map);map.flyTo=options=>{__tourFlights.push({duration:options.duration,center:options.center,zoom:options.zoom});return fly(options);};});
}
async function linked(page){await page.evaluate(()=>{
 const q={id:'linked-qa',type:'earthquake',mag:6.6,depth:10,coords:[-80.8,7.5],time:Date.now(),place:'Panama',source:'QA'};
 const a={id:'linked-bulletin',type:'tsunami',official:true,source:'PTWC',coords:q.coords,originTime:q.time,originMag:q.mag,time:Date.now(),place:'Panama',hazardNature:'warning',warningLevel:'Ameaça oficial',sev:4,affectedAreas:[{name:'Panama',category:'1 TO 3 METERS'},{name:'Costa Rica',category:'0.3 TO 1 METERS'},{name:'Nicaragua',category:'LESS THAN 0.3 METERS'}]};globalEvents=[q];globalAlerts=[a];showEventDetails(0,false);clearTimeout(cycleTimeout);
 });await page.waitForFunction(()=>map.getSource('tsunami-official-regions')?.serialize().data.features.length===6);
}
for(const width of [1280,390])test('linked earthquake keeps selection while touring coasts and interruption cleans up '+width,async({page})=>{
 test.setTimeout(120000);await boot(page,width);await linked(page);await page.clock.runFor(4000);await page.waitForFunction(()=>map.getSource('quake-impact')?.serialize().data.features.length>0);
 expect(await page.evaluate(()=>TsunamiPresentation.state().phase)).toBe('quake');expect(await page.evaluate(()=>map.getLayoutProperty('tsunami-regions-fill','visibility'))).toBe('none');
 await page.clock.fastForward(11000);await page.clock.runFor(500);
 expect(await page.evaluate(()=>TsunamiPresentation.state().phase)).toBe('coast');expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('linked-qa');await expect(page.locator('#pd-linked-presentation')).toContainText('Aviso de tsunami');expect(await page.evaluate(()=>map.getLayoutProperty('tsunami-regions-fill','visibility'))).toBe('visible');expect(await page.evaluate(()=>map.getLayoutProperty('quake-impact-fill','visibility'))).toBe('none');
 expect(await page.evaluate(()=>__tourFlights.at(-1).duration)).toBe(6000);await page.clock.runFor(2000);expect(await page.evaluate(()=>TsunamiPresentation.state().phase)).toBe('coast');
 await page.clock.fastForward(7500);expect(await page.evaluate(()=>TsunamiPresentation.state().phase)).toBe('quake');expect(await page.evaluate(()=>map.getLayoutProperty('tsunami-regions-fill','visibility'))).toBe('none');expect(await page.evaluate(()=>map.getLayoutProperty('quake-impact-fill','visibility'))).toBe('visible');expect(await page.evaluate(()=>__mgWaveFrontState.cameraPhase)).not.toMatch(/^p-/);
 await page.clock.fastForward(15000);await expect(page.locator('#pd-linked-presentation')).toContainText('Panamá');
 await page.evaluate(()=>{globalEvents.push({id:'larger-new',type:'earthquake',mag:7.5,depth:10,coords:[140,36],time:Date.now(),place:'Japan',source:'QA'});showEventDetails(1,false);clearTimeout(cycleTimeout);});await expect(page.locator('#pd-linked-presentation')).toHaveCount(0);expect(await page.evaluate(()=>TsunamiPresentation.state())).toBeNull();expect(await page.evaluate(()=>Boolean(map.getSource('tsunami-official-regions')))).toBe(false);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('larger-new');await page.clock.fastForward(30000);await expect(page.locator('#pd-linked-presentation')).toHaveCount(0);
});
test('late bulletin starts a related tour; missing origin does not guess and cancellation returns to quake',async({page})=>{
 await boot(page);await linked(page);await page.evaluate(()=>{globalAlerts[0]={...globalAlerts[0],originTime:undefined};TsunamiLinkedPanel.refresh();});expect(await page.evaluate(()=>TsunamiPresentation.state())).toBeNull();
 await page.evaluate(()=>{globalAlerts[0]={...globalAlerts[0],originTime:globalEvents[0].time};TsunamiLinkedPanel.refresh();});await expect(page.locator('#pd-linked-presentation')).toContainText('Sismo com boletim');await page.clock.fastForward(15000);expect(await page.evaluate(()=>TsunamiPresentation.state().phase)).toBe('coast');
 await page.evaluate(()=>{globalAlerts[0]={...globalAlerts[0],cancelled:true,warningLevel:'Encerrado'};TsunamiLinkedPanel.refresh();});expect(await page.evaluate(()=>TsunamiPresentation.state())).toBeNull();expect(await page.evaluate(()=>Boolean(map.getSource('tsunami-official-regions')))).toBe(false);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('linked-qa');await expect(page.locator('#pd-tsunami-link')).toContainText('Encerrado');
});
for(const width of [1280,390])test('menu linked demo visits every sample coast, blue is final, no fake records '+width,async({page})=>{
 test.setTimeout(120000);await boot(page,width);const before=await page.evaluate(()=>{map.jumpTo({center:[12,32],zoom:4});return {center:map.getCenter().toArray(),zoom:map.getZoom(),selected:eventoSelecionadoId};});
 await page.evaluate(()=>CardEffectDemo.open());await page.locator('#card-fx-demo-type').selectOption('tsunami');await expect(page.locator('#card-fx-demo-tsunami-mode')).toHaveValue('linked');await page.locator('#card-fx-demo-play').click();await page.waitForFunction(()=>TsunamiPresentation.state()?.demo);
 await expect(page.locator('#card-fx-demo-status')).toContainText('120 s');await expect(page.locator('#pd-linked-presentation')).toContainText('TESTE');expect(await page.evaluate(()=>({events:globalEvents.length,alerts:globalAlerts.length,selected:eventoSelecionadoId}))).toEqual({events:0,alerts:0,selected:before.selected});
 const started=await page.evaluate(()=>Date.now());const seen=[];
 for(let i=0;i<4;i++){
  await page.clock.fastForward(15000);await page.clock.runFor(200);const state=await page.evaluate(()=>TsunamiPresentation.state());expect(state.phase).toBe('coast');seen.push(state.stopName);expect(await page.evaluate(()=>TsunamiPresentation.ownsCamera('tsunami-linked-demo-quake'))).toBe(true);
  if(process.env.TSUNAMI_VISUAL_SATELLITE==='1'&&i===1){await page.clock.runFor(6000);await page.screenshot({path:'/tmp/linked-tsunami-demo-'+width+'.png'});await page.clock.fastForward(3800);}else await page.clock.fastForward(9800);
  expect(await page.evaluate(()=>TsunamiPresentation.state().phase)).toBe('quake');
 }
 expect(seen[0]).toBe('Todas as regiões indicadas');expect(new Set(seen.slice(1)).size).toBe(3);
 await page.clock.fastForward(started+104000-await page.evaluate(()=>Date.now())+100);expect(await page.evaluate(()=>TsunamiPresentation.state().phase)).toBe('blue');await expect(page.locator('#pd-linked-presentation')).toContainText('passagem final');await page.clock.fastForward(6000);expect(await page.evaluate(()=>TsunamiPresentation.state().phase)).toBe('quake');
 await page.getByRole('button',{name:'Parar',exact:true}).click();await expect(page.locator('#pd-linked-presentation')).toHaveCount(0);await expect(page.locator('#tsunami-map-legend')).toHaveCount(0);expect(await page.evaluate(()=>({center:map.getCenter().toArray(),zoom:map.getZoom()}))).toEqual({center:before.center,zoom:before.zoom});
});
test('pause holds the camera; stopping a demo restores the selected earthquake painting',async({page})=>{
 await boot(page);await linked(page);await page.clock.runFor(4000);await page.waitForFunction(()=>__mgSeismicImpactState?.features>0);await page.clock.fastForward(11000);await page.clock.runFor(500);expect(await page.evaluate(()=>TsunamiPresentation.state().phase)).toBe('coast');await page.getByRole('button',{name:'Pausar passeio',exact:true}).click({timeout:5000});const paused=await page.evaluate(()=>TsunamiPresentation.state());expect(paused.paused).toBe(true);await page.clock.fastForward(30000);expect(await page.evaluate(()=>TsunamiPresentation.state().phase)).toBe(paused.phase);
 await page.evaluate(()=>CardEffectDemo.preview('tsunami','linked'));await page.waitForFunction(()=>TsunamiPresentation.state()?.demo);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('linked-qa');await page.getByRole('button',{name:'Parar',exact:true}).click();await page.waitForFunction(()=>__mgSeismicImpactState?.id==='linked-qa'&&__mgSeismicImpactState.features>0);expect(await page.evaluate(()=>TsunamiPresentation.state().quakeId)).toBe('linked-qa');expect(await page.evaluate(()=>TsunamiPresentation.state().demo)).toBe(false);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('linked-qa');
});

test('independent bulletin tours its coasts without guessing an earthquake',async({page})=>{
 await boot(page);await page.evaluate(()=>{const a={id:'standalone-tour',type:'tsunami',official:true,source:'PTWC',coords:[-80.8,7.5],time:Date.now(),place:'Panamá',hazardNature:'warning',warningLevel:'Aviso',affectedAreas:[{name:'Panamá',category:'1 TO 3 METERS'},{name:'Costa Rica',category:'0.3 TO 1 METERS'}]};globalAlerts=[a];showAlertDetails(a,false);clearTimeout(cycleTimeout);});await page.waitForFunction(()=>TsunamiMap.stops().length===3);await expect.poll(()=>page.evaluate(()=>__tourFlights.length)).toBeGreaterThan(0);expect(await page.evaluate(()=>TsunamiPresentation.state())).toBeNull();const n=await page.evaluate(()=>__tourFlights.length);await page.clock.fastForward(10000);expect(await page.evaluate(()=>__tourFlights.length)).toBe(n+1);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('standalone-tour');await expect(page.locator('#tsunami-map-legend')).toContainText('Panamá');
});
