const {test,expect}=require('@playwright/test');test.use({serviceWorkers:'block',reducedMotion:'reduce'});
async function boot(page){const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.route('**/*',r=>(new URL(r.request().url()).origin===base||(process.env.TSUNAMI_VISUAL_SATELLITE==='1'&&r.request().url().includes('server.arcgisonline.com')))?r.continue():r.abort());await page.goto(base+'/?verify=tsunami-regions',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__mgMapReady&&!__fetchGlobalFeedsEmAndamento&&window.TsunamiMap);await page.evaluate(()=>{pausarBuscas();PeriodicScheduler.cancel('correlation');clearTimeout(cycleTimeout);stopWaveFront();stopFeltZone();map.stop();globalAlerts=[];globalEvents=[];pendingNewCameraQuakes.clear();PresentationLimits.clear();});}
function alert(){return {id:'PTWC-coasts',type:'tsunami',source:'PTWC',official:true,feedKey:'PTWC-WEPA40',time:Date.now(),coords:[-80.8,7.5],place:'Panama',hazardNature:'warning',warningLevel:'Ameaça oficial',sev:4,affectedAreas:[{name:'Panama',category:'1 TO 3 METERS'},{name:'Peru',category:'LESS THAN 0.3 METERS'}]};}
for(const width of [1280,390])test('published regions paint coasts, cancellation changes color and next event clears layers '+width,async({page})=>{
 await page.setViewportSize({width,height:900});await boot(page);const a=alert();await page.evaluate(a=>{globalAlerts=[a];showAlertDetails(a,false);clearTimeout(cycleTimeout);map.stop();},a);
 await expect(page.locator('#tsunami-map-legend')).toContainText('Previsão de 1 a 3 m');await expect(page.locator('#tsunami-map-legend')).toContainText('referência geográfica');
 expect(await page.evaluate(()=>[...new Set(map.getSource('tsunami-official-regions').serialize().data.features.map(f=>f.properties.color))])).toEqual(['#fb7148','#2dd4bf']);expect(await page.evaluate(()=>map.getStyle().layers.filter(l=>l.source==='tsunami-official-regions').every(l=>l.type==='fill'))).toBe(true);
 await expect(page.locator('#tsunami-map-legend')).toContainText('Não representa inundação');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 if(width===390)await page.screenshot({path:'/tmp/tsunami-painted-mobile.png'});
 if(width===1280){await page.locator('#tsunami-map-legend button').click();expect(await page.evaluate(()=>Number.isFinite(map.getZoom()))).toBe(true);if(process.env.TSUNAMI_VISUAL_SATELLITE==='1'){await page.evaluate(()=>map.jumpTo({center:centroCompensado(-80.5,8.5,6.5),zoom:6.5}));await page.waitForTimeout(3000);}await page.screenshot({path:'/tmp/tsunami-painted-coasts.png'});}
 await page.evaluate(()=>{globalAlerts[0]={...globalAlerts[0],cancelled:true,hazardNature:'bulletin',warningLevel:'Encerrado'};showAlertDetails(globalAlerts[0],false,true);});await expect(page.locator('#tsunami-map-legend')).toContainText('Encerrado');expect(await page.evaluate(()=>map.getSource('tsunami-official-regions').serialize().data.features.every(f=>f.properties.color==='#94a3b8'))).toBe(true);
 await page.evaluate(()=>{const q={id:'other-quake',type:'earthquake',mag:2,depth:10,time:Date.now(),coords:[26,36],place:'Turkey',source:'QA'};globalEvents=[q];showEventDetails(0,false);clearTimeout(cycleTimeout);});await expect(page.locator('#tsunami-map-legend')).toHaveCount(0);expect(await page.evaluate(()=>Boolean(map.getSource('tsunami-official-regions')))).toBe(false);
});
test('late coastal asset cannot paint a different selection',async({page})=>{
 await boot(page);let release;await page.route('**/ne-50m-coastal-regions.geojson?**',async r=>{await new Promise(ok=>release=ok);await r.fulfill({json:{type:'FeatureCollection',features:[]}});});
 await page.evaluate(a=>{globalAlerts=[a];showAlertDetails(a,false);clearTimeout(cycleTimeout);},alert());await expect.poll(()=>Boolean(release)).toBe(true);
 await page.evaluate(()=>{globalEvents=[{id:'fresh',type:'earthquake',mag:2.5,depth:5,coords:[30,38],time:Date.now(),place:'Turkey',source:'QA'}];showEventDetails(0,false);clearTimeout(cycleTimeout);});release();await page.waitForTimeout(100);await expect(page.locator('#tsunami-map-legend')).toHaveCount(0);expect(await page.evaluate(()=>Boolean(map.getSource('tsunami-official-regions')))).toBe(false);
});
test('official warning polygons are filled without downloading a coastal reference; missing scope stays explicit',async({page})=>{
 await boot(page);let requests=0;await page.route('**/ne-50m-coastal-regions.geojson?**',r=>{requests++;return r.abort();});const a={...alert(),affectedAreas:[],coords:[-123.5,45.5],coordinateRole:'warning-area',warningGeometry:{type:'Polygon',coordinates:[[[-123,45],[-124,45],[-124,46],[-123,45]]]}};
 await page.evaluate(a=>{globalAlerts=[a];showAlertDetails(a,false);clearTimeout(cycleTimeout);},a);await expect(page.locator('#tsunami-map-legend')).toContainText('Área publicada pela autoridade');expect(requests).toBe(0);expect(await page.evaluate(()=>map.getSource('tsunami-official-regions').serialize().data.features[0].properties.kind)).toBe('official');
 await page.evaluate(()=>{globalAlerts[0]={...globalAlerts[0],warningGeometry:null,hazardNature:'bulletin'};showAlertDetails(globalAlerts[0],false,true);});await expect(page.locator('#tsunami-map-legend')).toContainText('não fornece regiões');expect(await page.evaluate(()=>map.getSource('tsunami-official-regions').serialize().data.features.length)).toBe(0);
});
for(const width of [1280,390])test('repeatable tsunami demo paints without records and restores camera '+width,async({page})=>{
 await page.setViewportSize({width,height:900});await boot(page);
 const before=await page.evaluate(()=>{map.jumpTo({center:[12,32],zoom:4});return {center:map.getCenter().toArray(),zoom:map.getZoom(),selected:eventoSelecionadoId,events:globalEvents.length,alerts:globalAlerts.length};});
 await page.evaluate(()=>CardEffectDemo.open());await page.locator('#card-fx-demo-type').selectOption('tsunami');await expect(page.locator('#card-fx-demo-tsunami-options')).toBeVisible();await page.locator('#card-fx-demo-play').click();
 await expect(page.locator('#tsunami-map-legend')).toContainText('Cenário fictício');await expect(page.locator('#card-fx-demo-status')).toContainText('TESTE');
 expect(await page.evaluate(()=>[...new Set(map.getSource('tsunami-official-regions').serialize().data.features.map(f=>f.properties.color))])).toEqual(['#fb7148','#fbbf24','#2dd4bf']);
 expect(await page.evaluate(()=>({selected:eventoSelecionadoId,events:globalEvents.length,alerts:globalAlerts.length}))).toEqual({selected:before.selected,events:before.events,alerts:before.alerts});
 await page.evaluate(()=>runAutoCycle());await expect(page.locator('#tsunami-map-legend')).toContainText('TESTE');
 await page.getByRole('button',{name:'Parar',exact:true}).click();await expect(page.locator('#tsunami-map-legend')).toHaveCount(0);expect(await page.evaluate(()=>({center:map.getCenter().toArray(),zoom:map.getZoom()}))).toEqual({center:before.center,zoom:before.zoom});
 for(const [mode,color] of [['information','#38bdf8'],['cancelled','#94a3b8']]){await page.evaluate(mode=>CardEffectDemo.preview('tsunami',mode),mode);await expect(page.locator('#tsunami-map-legend')).toContainText('TESTE');expect(await page.evaluate(()=>map.getSource('tsunami-official-regions').serialize().data.features.every(f=>f.properties.color))).toBe(true);expect(await page.evaluate(()=>[...new Set(map.getSource('tsunami-official-regions').serialize().data.features.map(f=>f.properties.color))])).toEqual([color]);}
 await page.evaluate(()=>{const q={id:'real-next',type:'earthquake',mag:2,depth:10,time:Date.now(),coords:[26,36],place:'Turkey',source:'QA'};globalEvents=[q];showEventDetails(0,false);clearTimeout(cycleTimeout);});await expect(page.locator('#tsunami-map-legend')).toHaveCount(0);await expect(page.locator('#card-fx-demo-status')).toHaveCount(0);expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('real-next');
});
