const {test,expect}=require('@playwright/test');
test.use({serviceWorkers:'block',reducedMotion:'reduce'});
for(const width of [1280,390])test('known volcano escalation, deduplication and M5 precedence '+width,async({page})=>{
 const base=process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173';await page.setViewportSize({width,height:844});await page.route('**/*',r=>new URL(r.request().url()).hostname===new URL(base).hostname?r.continue():r.abort());await page.goto(base+'/?verify='+Date.now());await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento&&window.__mgMapReady);
 await page.evaluate(async()=>{pausarBuscas();await fetchVolcanoes();globalEvents=[];globalAlerts=[];knownAlertIds.clear();for(const f of ['volcanoGdacs','volcanoUsgs','volcanoVaac'])fontesBooted.delete(f);clearTimeout(cycleTimeout);stopWaveFront();stopFeltZone();SeismicCinema.stop();eventoSelecionadoId=null;EventStore.selectedId=null;window.__mgRevisionProtectedId=null;window.__mgHoldEndsAt=0;window.__mgLiveQuakeId=null;pendingNewCameraQuakes.clear();pendingQuakeRevisions.clear();geoFilter='all';sidebarFilter='all';soCriticos=false;window.__volcanoSounds=[];playAlertTone=k=>__volcanoSounds.push(k);notificarNavegador=()=>{};fetchGdacsEvents=async()=>[];fetchUSGSVolcanoProfessional=async()=>({all:[],elevated:[]});window.__volcanoReport={name:'Ambae QA',coords:[167.83,-15.4],source:'Smithsonian GVP',detail:'Atividade monitorada',time:Date.now()};fetchGlobalVolcanoAdvisories=async()=>[__volcanoReport];await fetchVolcanoes();clearTimeout(cycleTimeout);});
 expect(await page.evaluate(()=>__volcanoSounds)).toEqual([]);
 await page.evaluate(async()=>{__volcanoReport.detail='New lava lake occupies crater from two vents. Effusive eruption resumes.';await fetchVolcanoes();clearTimeout(cycleTimeout);});
 expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('vaac-ambae-qa');expect(await page.evaluate(()=>__volcanoSounds)).toEqual(['volcano']);await expect(page.locator('#pd-local')).toContainText('Ambae QA');
 await page.evaluate(async()=>{await fetchVolcanoes();clearTimeout(cycleTimeout);globalEvents=[{id:'low',mag:2.4,coords:[25,35],time:Date.now(),place:'Low QA',source:'EMSC',depth:10}];queueNewCameraQuakes(globalEvents);focusNextNewCameraQuake();});expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('vaac-ambae-qa');expect(await page.evaluate(()=>__volcanoSounds)).toEqual(['volcano']);
 await page.evaluate(()=>{globalEvents.push({id:'strong',mag:5.2,coords:[22,38],time:Date.now(),place:'Strong QA',source:'EMSC',depth:10});queueNewCameraQuakes([globalEvents[1]]);focusNextNewCameraQuake();clearTimeout(cycleTimeout);});expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('strong');
 await page.evaluate(async()=>{__volcanoReport.aviationColor='red';await fetchVolcanoes();clearTimeout(cycleTimeout);});expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('strong');expect(await page.evaluate(()=>__volcanoSounds)).toEqual(['volcano']);
 await page.evaluate(()=>{stopWaveFront();clearTimeout(window.__mgWaveDelayT);window.__mgHoldEndsAt=0;window.__mgLiveQuakeUntil=0;window.__mgRevisionProtectedUntil=0;VolcanoPriority.focus();clearTimeout(cycleTimeout);});expect(await page.evaluate(()=>eventoSelecionadoId)).toBe('vaac-ambae-qa');expect(await page.evaluate(()=>globalAlerts[0]._volcanoEscalation)).toBe('Elevação do nível de alerta');expect(await page.evaluate(()=>__volcanoSounds)).toEqual(['volcano','volcano']);
});
