const {test,expect}=require('@playwright/test');
test.use({serviceWorkers:'block'});
for(const width of [1280,390])test('cratera de monitoramento no Menu e no evento real preserva dados, revisão e controles '+width,async({page})=>{
 test.setTimeout(120000);
 await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 await page.setViewportSize({width,height:844});await page.goto('/',{waitUntil:'domcontentloaded'});await page.evaluate(()=>OptionalFeatures.effect("volcano"));
 await page.waitForFunction(()=>!__fetchGlobalFeedsEmAndamento&&!!window.CardVolcanoMonitoring);
 const errors=[];page.on('pageerror',e=>{if(e.message!=='Failed to fetch')errors.push(e.message);});
 await page.evaluate(()=>{
  const item={id:'crater-real',type:'volcano',eruptionStatus:'Sem atividade eruptiva',detail:'Em monitoramento',source:'QA',coords:[-155.29,19.42],time:Date.now(),place:'Vulcão de teste'};
  globalAlerts=[item];upsertAlert(item);showAlertDetails(item,false);clearTimeout(cycleTimeout);clearTimeout(window.__mgRadarDelayT);clearTimeout(window.__mgWaveDelayT);
  window.__craterSound=0;window.__craterFlight=0;window.playEarthquakeSound=()=>__craterSound++;map.flyTo=()=>__craterFlight++;
 });
 await expect(page.locator('.pd-volcano-monitor')).toHaveAttribute('data-texture','photograph');
 await expect(page.locator('.pd-cinema-layer')).toHaveAttribute('data-demo','false');
 await expect(page.locator('.pd-cinema-footage,.pd-cinema-heat,.pd-cinema-film,.pd-weather-material')).toHaveCount(0);
 if(width===390)await page.evaluate(()=>{document.body.classList.remove('mobile-details-mid');document.body.classList.add('mobile-details-open');});
 const canvas=page.locator('.pd-volcano-monitor');
 const pixels=()=>canvas.evaluate(el=>Array.from(el.getContext('2d').getImageData(0,0,el.width,el.height).data).filter((v,i)=>i%20===0));
 const first=await pixels();expect(new Set(first).size).toBeGreaterThan(30);
 await page.waitForTimeout(1200);expect(await pixels()).not.toEqual(first);
 await expect(page.locator('#pd-local')).toContainText('Vulcão de teste');
 await page.locator('#painel-direito').screenshot({path:'/tmp/volcano-monitoring-'+width+'.png'});
 expect(await page.locator('#pd-focus-btn').evaluate(el=>{const r=el.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('#pd-focus-btn')===el;})).toBe(true);
 const original=await canvas.elementHandle();
 await page.evaluate(()=>{const item={...EventStore.getSelected(),place:'Boletim atualizado'};upsertAlert(item);showAlertDetails(item,false,true);clearTimeout(cycleTimeout);});
 expect(await original.evaluate(el=>el.isConnected)).toBe(true);await expect(page.locator('#pd-local')).toContainText('Boletim atualizado');
 const before=await page.evaluate(()=>({events:JSON.stringify(globalAlerts),selected:EventStore.selectedId,text:document.getElementById('pd-local').textContent}));
 await page.evaluate(()=>CardEffectDemo.preview('volcano-monitoring'));
 await expect(canvas).toHaveAttribute('data-texture','photograph');await expect(page.locator('.pd-cinema-layer')).toHaveAttribute('data-demo','true');
 expect(await page.evaluate(()=>({events:JSON.stringify(globalAlerts),selected:EventStore.selectedId,text:document.getElementById('pd-local').textContent}))).toEqual(before);
 expect(await page.evaluate(()=>[__craterSound,__craterFlight])).toEqual([0,0]);
 await page.evaluate(()=>CardEffectDemo.stop());await expect(canvas).toHaveCount(1);await expect(page.locator('.pd-cinema-layer')).toHaveAttribute('data-demo','false');
 await page.evaluate(()=>{const item={...EventStore.getSelected(),eruptionStatus:'Em erupção',detail:'Fluxo de lava ativo · sem cinzas'};upsertAlert(item);showAlertDetails(item,false,true);clearTimeout(cycleTimeout);});
 await expect(canvas).toHaveCount(0);await expect(page.locator('#painel-direito')).not.toHaveClass(/pd-volcano-monitoring/);await expect(page.locator('.pd-cinema-layer')).toHaveAttribute('data-material','lava');
 await page.evaluate(()=>CardEffectDemo.preview('volcano-monitoring'));await expect(canvas).toHaveCount(1);
 await page.emulateMedia({reducedMotion:'reduce'});await expect(page.locator('.pd-volcano-monitor,.pd-cinema-layer')).toHaveCount(0);await expect(page.locator('#painel-direito')).not.toHaveClass(/pd-volcano-monitoring/);
 expect(errors).toEqual([]);
});
test('sem fotografia, a reserva desenha uma cratera detalhada e limpa a carga pendente',async({page})=>{
 await page.route('**/volcano-crater.jpg',r=>r.abort());
 await page.goto('/',{waitUntil:'domcontentloaded'});await page.evaluate(()=>OptionalFeatures.effect("volcano"));await page.waitForFunction(()=>!!window.CardVolcanoMonitoring);
 const result=await page.evaluate(()=>{
  const scene=CardVolcanoMonitoring.create({type:'volcano',hot:false,ash:false,lava:false},false);scene.resize(320,600);scene.draw(2);
  const ctx=scene.canvas.getContext('2d'),data=ctx.getImageData(0,0,scene.canvas.width,scene.canvas.height).data;
  const values=new Set(Array.from(data).filter((v,i)=>i%4===0)),at=(x,y)=>Array.from(ctx.getImageData(x,y,1,1).data);
  const sample={unique:values.size,center:at(160,280),edge:at(280,280),texture:scene.canvas.dataset.texture};
  document.body.append(scene.canvas);scene.destroy();sample.connected=scene.canvas.isConnected;
  sample.active=CardVolcanoMonitoring.create({type:'volcano',hot:true,ash:true,lava:false},false);
  return sample;
 });
 expect(result.unique).toBeGreaterThan(30);expect(result.center).not.toEqual(result.edge);expect(result.texture).toBe('procedural');expect(result.connected).toBe(false);expect(result.active).toBeNull();
});
