"""Build the offline fonts and simplified Natural Earth land used by the daily PNG.

Requires Pillow, fonts-noto-core and fonts-open-sans. Noto Serif Display is
SIL OFL; this Open Sans release is Apache-2.0. Natural Earth is public domain.
"""
import base64
import io
import json
import math
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SERIF = '/usr/share/fonts/truetype/noto/NotoSerifDisplay-Regular.ttf'
SANS = '/usr/share/fonts/truetype/open-sans/OpenSans-Regular.ttf'
BOLD = '/usr/share/fonts/truetype/open-sans/OpenSans-Semibold.ttf'
CHARS = ''.join(dict.fromkeys(''.join(chr(i) for i in range(32, 127)) +
    'ÁÀÂÃÄÅÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑáàâãäåéèêëíìîïóòôõöúùûüçñ·–—°'))
NUMBERS = ' 0123456789M,.+?-'
SPECS = {
    'brand': (BOLD, 18, CHARS), 'small': (SANS, 11, CHARS),
    'country': (BOLD, 11, CHARS), 'tag': (SANS, 12, CHARS),
    'caption': (SANS, 14, CHARS), 'detail': (SANS, 17, CHARS), 'prefix': (SANS, 23, ' M?'),
    'heading': (SERIF, 73, CHARS), 'subtitle': (SERIF, 60, CHARS),
    'heroName': (SERIF, 29, CHARS), 'title': (SERIF, 25, CHARS),
    'hero': (SERIF, 107, NUMBERS), 'magnitude': (SERIF, 38, NUMBERS),
    'total': (SERIF, 52, NUMBERS), 'band': (SERIF, 28, NUMBERS),
    'section': (SERIF, 21, CHARS),
}

def atlas(path, size, chars):
    font = ImageFont.truetype(path, size)
    boxes = {ch: font.getbbox(ch, anchor='ls') for ch in chars}
    top = min(b[1] for b in boxes.values())
    bottom = max(b[3] for b in boxes.values())
    widths = {ch: max(2, b[2] - b[0] + 2) for ch, b in boxes.items()}
    img = Image.new('RGBA', (sum(widths.values()), bottom - top + 2))
    draw = ImageDraw.Draw(img)
    glyphs, x = {}, 0
    for ch in chars:
        left = boxes[ch][0]
        draw.text((x + 1 - left, 1 - top), ch, font=font, fill='white', anchor='ls')
        glyphs[ch] = [x, widths[ch], round(font.getlength(ch), 3), 1 - left]
        x += widths[ch]
    png = io.BytesIO()
    img.save(png, format='PNG', optimize=True)
    return {'cellH': img.height, 'glyphs': glyphs, 'b64': base64.b64encode(png.getvalue()).decode()}

def distance_sq(p, a, b):
    dx, dy = b[0] - a[0], b[1] - a[1]
    t = 0 if dx == dy == 0 else max(0, min(1, ((p[0]-a[0])*dx + (p[1]-a[1])*dy)/(dx*dx+dy*dy)))
    return (p[0]-a[0]-t*dx)**2 + (p[1]-a[1]-t*dy)**2

def simplify(points, tolerance=.09):
    if len(points) < 4:
        return points
    stack, keep = [(0, len(points)-1)], {0, len(points)-1}
    while stack:
        a, b = stack.pop()
        if b-a < 2:
            continue
        index = max(range(a+1, b), key=lambda i: distance_sq(points[i], points[a], points[b]))
        if distance_sq(points[index], points[a], points[b]) > tolerance*tolerance:
            keep.add(index)
            stack.extend([(a, index), (index, b)])
    return [[round(v, 4) for v in points[i]] for i in sorted(keep)]

geo = json.loads((ROOT/'assets/seismic/ne-50m-land.geojson').read_text())
land = []
for feature in geo['features']:
    geom = feature['geometry']
    polygons = [geom['coordinates']] if geom['type'] == 'Polygon' else geom['coordinates']
    for polygon in polygons:
        rings = [simplify(ring) for ring in polygon]
        rings = [ring for ring in rings if len(ring) >= 4]
        if rings:
            land.append(rings)

fonts = {name: atlas(*spec) for name, spec in SPECS.items()}
dest = ROOT/'summary-editorial-assets.mjs'
dest.write_text('// Generated by tools/build-summary-editorial-assets.py. Noto: SIL OFL; Open Sans: Apache-2.0; Natural Earth: public domain.\n'
    + 'export const SUMMARY_EDITORIAL_TYPOGRAPHY = ' + json.dumps(fonts, ensure_ascii=False, separators=(',', ':')) + ';\n'
    + 'export const SUMMARY_MAP_LAND = ' + json.dumps(land, separators=(',', ':')) + ';\n')
print(f'{dest.name}: {dest.stat().st_size:,} bytes; {sum(len(r) for p in land for r in p):,} land points')
