const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function boot(){
 const style=()=>({setProperty(k,v){this[k]=v},removeProperty(k){delete this[k]}});
 const context={rect(){},fill(){},setLineDash(){},translate(){},rotate(){},setTransform(){},clearRect(){},createRadialGradient(){return {addColorStop(){}}},createLinearGradient(){return {addColorStop(){}}},fillRect(){},beginPath(){},ellipse(){},stroke(){},moveTo(){},lineTo(){},closePath(){},save(){},restore(){},clip(){},drawImage(){},quadraticCurveTo(){}};
 function el(tag='div'){return {tag,cloneNode(){return el(tag)},children:[],dataset:{},style:style(),classList:{add(){},remove(){},contains(){return false}},clientWidth:390,clientHeight:600,scrollTop:0,setAttribute(){},addEventListener(){},removeEventListener(){},append(n){this.children.push(n)},querySelector(sel){return this.children.find(c=>'.'+c.className===sel)},querySelectorAll(){return []},getContext(){return context},remove(){this.removed=true}}}
 const panel=el();let frame,wind=0,windOptions,restores=0;const document={hidden:false,body:{classList:{contains:()=>true}},createElement:el,createElementNS:(_,tag)=>el(tag),getElementById:id=>id==='painel-direito'?panel:null,addEventListener(){}};
 const reduced={matches:false,addEventListener(){}};const sandbox={document,performance:{now:()=>0},devicePixelRatio:1,matchMedia:q=>q.includes('reduced')?reduced:{matches:true},ResizeObserver:class {observe(){ }disconnect(){}},requestAnimationFrame:f=>(frame=f,1),cancelAnimationFrame(){},setTimeout:()=>1,clearTimeout(){},Math};sandbox.window={addEventListener(){},triggerWindLetters:(_,options)=>{wind++;windOptions=options},restoreWindLetters:()=>restores++};
 vm.runInNewContext(fs.readFileSync('js/cinematic-card.js','utf8'),sandbox);
 return {panel,api:sandbox.window.CinematicCard,frame:t=>frame(t),get wind(){return wind},get windOptions(){return windOptions},get restores(){return restores},reduced};
}
test('rain contacts the front, gusts start, and stop releases surface and text',()=>{const s=boot();assert.equal(s.api.start({id:'rain',type:'storm',detail:'Trovoadas',__cinemaDemo:true}),true);const front=s.panel.children.find(n=>n.className==='pd-cinema-contact');assert.ok(front.children.some(n=>n.className==='pd-cinema-lenses'));s.frame(1200);assert.equal(s.wind,1);s.api.stop();assert.equal(front.removed,true);assert.ok(s.restores>=1)});
test('flood rises across the card and clears its geometry when replaced',()=>{const s=boot();s.api.start({id:'water',type:'flood'});s.frame(1000);const first=parseFloat(s.panel.style['--pd-water-top']);s.frame(10000);assert.ok(parseFloat(s.panel.style['--pd-water-top'])<first);s.api.start({id:'wind',type:'wind'});assert.equal(s.panel.style['--pd-water-top'],undefined);s.api.stop()});
test('reduced motion creates no contact surface or gusts',()=>{const s=boot();s.reduced.matches=true;assert.equal(s.api.start({id:'quiet',type:'hurricane'}),false);assert.equal(s.wind,0);assert.equal(s.panel.children.length,0)});
test('cyclones animate all card typography and release pressure when duration ends',()=>{const s=boot();assert.equal(s.api.start({id:'cyclone',type:'hurricane',windKmh:150,coords:[130,-18]},2000),true);assert.equal(s.windOptions.controlled,true);assert.equal(s.windOptions.allText,true);const layer=s.panel.children.find(n=>n.className==='pd-cinema-layer');assert.equal(layer.dataset.cycloneStage,'mature');assert.equal(layer.dataset.rotationDirection,-1);s.frame(1200);assert.ok(parseFloat(s.panel.style['--pd-wind-pressure'])>0);s.frame(2100);assert.equal(s.api.isActive(),false);assert.equal(s.panel.style['--pd-wind-x'],undefined);assert.equal(s.panel.style['--pd-wind-pressure'],undefined);assert.equal(layer.removed,true)});
