const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function fixture(){let now=10000,next=0;const timers=new Map(),listeners={};const document={hidden:false,addEventListener:(k,f)=>listeners[k]=f};const context={window:{},document,Date:{now:()=>now},Promise,console:{warn(){}},setTimeout:(f,ms)=>{timers.set(++next,{f,at:now+ms});return next},clearTimeout:id=>timers.delete(id)};vm.runInNewContext(fs.readFileSync('js/periodic-scheduler.js','utf8'),context);return {context,s:context.window.PeriodicScheduler,timers,async advance(ms){now+=ms;await Promise.resolve();await Promise.resolve();await Promise.resolve();for(let n=0;n<100;n++){const ready=[...timers].find(([,t])=>t.at<=now);if(!ready)break;timers.delete(ready[0]);ready[1].f();await Promise.resolve();await Promise.resolve();await Promise.resolve();}},visibility(hidden){document.hidden=hidden;listeners.visibilitychange();}}}
test('one timer, registration deduplication, intervals and manual pause',async()=>{const f=fixture();let a=0,b=0;const fn=()=>a++;f.s.every('a',fn,0,1000);f.s.every('a',fn,0,1000);f.s.every('b',()=>b++,500,2000);assert.equal(f.timers.size,1);await f.advance(0);assert.equal(a,1);await f.advance(500);assert.equal(b,1);f.s.pause('feeds');assert.equal(f.timers.size,0);await f.advance(10000);assert.equal(a,1);f.s.resume('feeds');await f.advance(0);assert.equal(a,2);assert.equal(b,1);await f.advance(750);assert.equal(b,2);});
test('hidden tabs do no scheduled work; resuming staggers feeds without replay',async()=>{const f=fixture();let a=0,b=0,ui=0;f.s.every('a',()=>a++,0,1000);f.s.every('b',()=>b++,0,1000);f.s.every('ui',()=>ui++,0,1000,'ui');f.visibility(true);await f.advance(600000);assert.equal(a+b+ui,0);assert.equal(f.timers.size,0);f.visibility(false);await f.advance(0);assert.deepEqual([a,b,ui],[1,0,1]);await f.advance(750);assert.deepEqual([a,b,ui],[1,1,1]);});
test('inflight feeds do not overlap on focus or overrun and recover after rejection',async()=>{const f=fixture();let calls=0,reject;f.s.every('slow',()=>{calls++;return new Promise((_,r)=>reject=r)},0,1000);await f.advance(0);f.s.trigger('slow');await f.advance(60000);assert.equal(calls,1);reject(Error('offline'));await f.advance(0);await f.advance(1000);assert.equal(calls,2);});
test('cancel/replacement ignores completion of the old promise',async()=>{const f=fixture();let release,a=0;f.s.every('x',()=>new Promise(r=>release=r),0,1000);await f.advance(0);f.s.cancel('x');f.s.every('x',()=>a++,1000,1000);release();await f.advance(0);assert.equal(a,0);await f.advance(1000);assert.equal(a,1);assert.equal(f.timers.size,1);});
test('UI keeps running when feeds manually paused and hidden registrations wait',async()=>{const f=fixture();let a=0;f.s.pause('feeds');f.s.every('ui',()=>a++,0,1000,'ui');await f.advance(0);assert.equal(a,1);f.visibility(true);f.s.every('late',()=>a+=100,0,1000);await f.advance(1000);assert.equal(a,1);f.visibility(false);await f.advance(0);assert.equal(a,2);f.s.resume('feeds');await f.advance(0);assert.equal(a,102);});

test('core resume coalesces lifecycle signals and cannot resume while hidden',async()=>{const f=fixture();let calls=0;f.context.PeriodicScheduler=f.s;f.context.fetchGlobalFeeds=()=>{calls++;};const core=fs.readFileSync('js/nucleo-estado.js','utf8');vm.runInNewContext(core.slice(core.indexOf('const __buscasAgendadas ='),core.indexOf("document.addEventListener('visibilitychange'",core.indexOf('const __buscasAgendadas ='))),f.context);f.context.agendarBusca(f.context.fetchGlobalFeeds,0,45000);f.context.agendarBusca(f.context.fetchGlobalFeeds,0,45000);await f.advance(0);assert.equal(calls,1);f.context.retomarBuscas();f.context.retomarBuscas();await f.advance(0);assert.equal(calls,1);f.visibility(true);f.context.pausarBuscas();await f.advance(10000);f.context.retomarBuscas();assert.equal(f.timers.size,0);f.visibility(false);f.context.retomarBuscas();await f.advance(0);assert.equal(calls,2);});
