const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('js/orquestrador-feeds.js','utf8'),panel=fs.readFileSync('js/painel-e-lista.js','utf8');
function fn(s,n){const a=s.indexOf('function '+n+'(');return s.slice(a,s.indexOf('\n}',a)+2);}
function setup(){const shown=[],timers=[];const c=vm.createContext({document:{hidden:false},Date,console,Map,Set,window:{__mgRevisionProtectedId:'low',__mgRevisionProtectedUntil:Date.now()+90000,__mgHoldMag:2.4,__mgQuakeCameraPresented:new Map([['low',2.4]])},map:{isMoving:()=>false},globalEvents:[{id:'low',mag:2.4,time:Date.now()-6*60000},{id:'high',mag:5.2,time:Date.now()-9*60000}],eventoSelecionadoId:'low',activeAlertingIds:new Map(),cycleTimeout:null,setTimeout:f=>{timers.push(f);return timers.length;},clearTimeout(){},showEventDetails:(i)=>{shown.push(c.globalEvents[i].id);c.eventoSelecionadoId=c.globalEvents[i].id;c.window.__mgQuakeCameraPresented.set(c.eventoSelecionadoId,c.globalEvents[i].mag);},showNextAutoCycleItem:()=>false});vm.runInContext(fn(panel,'isWithinAutoCycleAge'),c);vm.runInContext(source.slice(source.indexOf('const pendingNewCameraQuakes'),source.indexOf('async function fetchGlobalFeeds')),c);vm.runInContext(fn(panel,'getAutoCycleProtectionRemaining')+'\n'+fn(panel,'scheduleNextAutoCycle')+'\n'+fn(panel,'runAutoCycle'),c);return{c,shown,timers};}
test('M5.2 preempts protected M2.4 even if a companion UI throws',()=>{const{c,shown}=setup();c.window.ElectionPanel={newQuakes(){throw Error('UI failure')}};c.queueNewCameraQuakes([c.globalEvents[1]]);assert.equal(c.focusNextNewCameraQuake(),true);assert.deepEqual(shown,['high']);});
test('scheduler checks a larger pending arrival before waiting on protection',()=>{const{c,shown,timers}=setup();c.queueNewCameraQuakes([c.globalEvents[1]]);c.scheduleNextAutoCycle(1000);timers.shift()();assert.deepEqual(shown,['high']);});
test('equal and smaller new arrivals still interrupt a protected hold -- every new quake is shown',()=>{const{c,shown}=setup();c.globalEvents[1].mag=1.9;c.queueNewCameraQuakes([c.globalEvents[1]]);assert.equal(c.focusNextNewCameraQuake(),true);assert.deepEqual(shown,['high']);});
test('revision raising a known quake to M5.2 preempts a protected M2.4',()=>{const{c,shown}=setup();c.queueQuakeRevisions([{...c.globalEvents[1],_previousMag:2.3}]);assert.equal(c.focusNextQuakeRevision(true),true);assert.deepEqual(shown,['high']);});
test('source-only revisions do not gain magnitude priority',()=>{const{c,shown}=setup();c.queueQuakeRevisions([{...c.globalEvents[1],_previousMag:5.2}]);assert.equal(c.focusNextQuakeRevision(true),false);assert.deepEqual(shown,[]);});
test('recover an unpresented new badge without replaying it continuously',()=>{const{c,shown}=setup();c.activeAlertingIds.set('high',Date.now()+180000);assert.equal(c.focusNextNewCameraQuake(),true);c.eventoSelecionadoId='low';assert.equal(c.focusNextNewCameraQuake(),false);assert.deepEqual(shown,['high']);});
test('historical unbadged larger catalog records never interrupt merely by existing',()=>{const{c,shown}=setup();assert.equal(c.focusNextNewCameraQuake(),false);assert.deepEqual(shown,[]);});
